### PR TITLE
Revert percent encoding in URLs.

### LINKED ISSUE #4458: AnyUrl escapes percent sign in URLs without TLD that are already escaped.
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using `AnyUrl` with a localhost URL (or any URL without a top level domain), if the provided URL already is encoded/escaped, pydantic will escape the percent sign again. When the domain has a TLD, it works perfectly fine. I've confirmed that the bug isn't present in 1.9.1. It seems to have been introduced in 1.10.0 and is still present in 1.10.1.

### Example Code

```Python
from pydantic import BaseModel, AnyUrl


class Foo(BaseModel):
    url: AnyUrl


class Bar(BaseModel):
    url: str


assert Foo(url='https://example.com/Foo%20Bar').url == 'https://example.com/Foo%20Bar'  # Passes
assert Bar(url='https://localhost/Foo%20Bar').url == 'https://localhost/Foo%20Bar'  # Passes
assert Foo(url='https://localhost/Foo%20Bar').url == 'https://localhost/Foo%20Bar'  # Fails: https://localhost/Foo%2520Bar
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.1
            pydantic compiled: True
                 install path: /home/afitter/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### LINKED ISSUE #4468: AnyUrl percent encoding (#3061) introduced v1.10.0 breaks database connection string
## Checks

- [x] I added a descriptive title to this issue
- [x] I have searched (google, github) for similar issues and couldn't find anything
- [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

## Bug
This bug-fix https://github.com/pydantic/pydantic/issues/3061 introduced percent encoding for the `query` attribute of `AnyUrl`. It lists a set of characters that get percent encoded and refers to the [url-spec](https://www.w3.org/Addressing/URL/url-spec.txt).

According to the url-spec, the `+` character is in the group of safe characters and **should not be encoded** (page 16 in the doc).

As a consequence of the introduced characters encoding, my database connection string to a MS SQL Server DB got unusable:

```
import pydantic


url = pydantic.AnyUrl.build(
    scheme="mssql+pyodbc",
    user="user",
    password="password",
    host="127.0.0.1",
    port="1433",
    path="/database",
    query="driver=ODBC+Driver+17+for+SQL+Server",
)
print(pydantic.VERSION)
print(url)


# 1.9.1
# mssql+pyodbc://user:password@127.0.0.1:1433/database?driver=ODBC+Driver+17+for+SQL+Server

# 1.10.1
# mssql+pyodbc://user:password@127.0.0.1:1433/database?driver=ODBC%2BDriver%2B17%2Bfor%2BSQL%2BServer
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.9.1
pydantic compiled: True
install path: C:\Users\xxx\PycharmProjects\xxx\venv\Lib\site-packages\pydantic
python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
platform: Windows-10-10.0.19044-SP0
optional deps. installed: ['typing-extensions']
```

It would be cool to have a MSSQLServerDsn similar to Postgres, Redis, or MongoDB instead of the general AnyUrl (https://pydantic-docs.helpmanual.io/usage/types/#urls).

### PR DESCRIPTION
**Pull request by samuelcolvin**
This reverts #4224.

fix #4458, fix #4468. Replaces #4469 and #4461.

There are a number of problems with #4224:
1. It re-encodes existing percent encoded URLs, this was reported in #4458 and could be fixed by #4469
2. It wrongly encoded `/`, this could also be fixed by #4469
3. It wrongly encoded `+`, this was reported in #4468 and could also be fixed by #4469
4. It would require us to rebuild virtually all URLs, currently we only rebuild URLs with "international" domains, if I enable `rebuild` for all URL validation, lots of tests fail, fixing those tests involves significant changes and we're well into the "this is not really suitable for a patch release" territory.

Therefore after some consideration and discussion with other pydantic maintainers (and with a heavy heart), I've decided the best approach is to remove percentage encoding from URL logic until V2.

Long term (e.g. in V2) I think we should use an external library (either in python or rust) to perform URL parsing and validation.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
please review.

**Review by hramezani — APPROVED** [review]
LGTM :+1:

**Comment by gmanny** [comment]
Sorry if this isn't the place to write this, but the now-reverted change was also what caused our DB connectivity problems because we used PostgresDsn to create a connection string for SQLAlchemy and the name of unix socket contained `:` characters.

Was very hard to debug because on Google Cloud Run you only get `File not found` and a vague error log about the URL-encoded name of the DB not being reachable. I think, we may not be alone with this, so it's worth releasing this fix as fast as possible.

**Comment by samuelcolvin** [comment]
For anyone interested, I've just implemented URL parsing as part of pydantic-core for V2, see pydantic/pydantic-core#317.

Feedback welcome.

**Pull request merged**
