### PR TITLE
ci: attempt to report coverage change as a comment on PRs

### PR DESCRIPTION
**Pull request by AlessandroMiola**
## Change Summary

Adds a CI step to report coverage changes as a comment on PRs. Based on https://github.com/marketplace/actions/python-coverage-comment, in turn referenced at https://coverage.readthedocs.io/en/latest/other.html#reporting-helpers.

## Related issue number

Addresses https://github.com/pydantic/pydantic/pull/9740#issuecomment-2186698277.

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [x] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by AlessandroMiola** [comment]
The solution is not working at the moment (still trying to understand why...). Issues:

- the comment does not get posted and the following annotations do appear (see - eg -https://github.com/pydantic/pydantic/actions/runs/9733143231)

      Notice: Starting action
      Notice: HTTP Request: GET https://api.github.com/repos/pydantic/pydantic "HTTP/1.1 200 OK"
      Notice: Generating comment for PR
      Notice: HTTP Request: GET https://api.github.com/repos/pydantic/pydantic/contents/data.json?ref=python-coverage-comment-action-data "HTTP/1.1 404 Not Found"
      Notice: HTTP Request: GET https://api.github.com/user "HTTP/1.1 403 Forbidden"
      Notice: HTTP Request: GET https://api.github.com/repos/pydantic/pydantic/issues/9796/comments "HTTP/1.1 200 OK"
      Notice: Adding new comment
      Notice: HTTP Request: POST https://api.github.com/repos/pydantic/pydantic/issues/9796/comments "HTTP/1.1 403 Forbidden"
      Notice: Cannot post comment. This is probably because this is an external PR, so it's expected. Ensure you have an additional `workflow_run` step configured as explained in the documentation (or alternatively, give up on PR comments for external PRs).
      Notice: Ending action
- the coverage reported within the [python-coverage-comment-action](https://github.com/pydantic/pydantic/actions/runs/9733143231/artifacts/1652940980) artifact does not coincide with the official one (97.22% vs 96.33%)

On a (completely unrelated) side note, I have been experimenting an issue when running `make test` locally since the addition of the `fail-fast` feature; this is strange as CI tests on Windows do pass. Failures (all in `test_fail_fast`) are similar to the following but do happen to all parametrizations but the `field-default` related ones. Anyway, I can open a dedicated issue. I was just wondering if anybody could reproduce (on Windows)

    tests\test_types.py:6724:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    pydantic\_internal\_model_construction.py:205: in __new__
        complete_model_class(
    pydantic\_internal\_model_construction.py:544: in complete_model_class
        schema = gen_schema.clean_schema(schema)
    pydantic\_internal\_generate_schema.py:452: in clean_schema
        schema = validate_core_schema(schema)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    schema = {'cls': <class 'tests.test_types.test_fail_fast.<locals>.Foo'>, 'config': {'title': 'Foo'}, 'custom_init': False, 'met...<bound method BaseModel.__get_pydantic_json_schema__ of <class 'tests.test_types.test_fail_fast.<locals>.Foo'>>]}, ...}
    
        def validate_core_schema(schema: CoreSchema) -> CoreSchema:
            if 'PYDANTIC_SKIP_VALIDATING_CORE_SCHEMAS' in os.environ:
                return schema
    >       return _validate_core_schema(schema)
    E       pydantic_core._pydantic_core.SchemaError: Invalid Schema:
    E       model.schema.model-fields.fields.a.schema.frozenset.fail_fast
    E         Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    
    pydantic\_internal\_core_utils.py:568: SchemaError

**Comment by sydney-runkle** [comment]
@AlessandroMiola,

Thanks for your work on this. I'll try opening a PR with your changes and see if we can get things working!

**Comment by sydney-runkle** [comment]
> On a (completely unrelated) side note, I have been experimenting an issue when running make test locally since the addition of the fail-fast feature; this is strange as CI tests on Windows do pass. Failures (all in test_fail_fast) are similar to the following but do happen on all parametrizations but the field-default related ones. Anyway, I can open a dedicated issue. I was just wondering if anybody could reproduce (on Windows)

Do you have `v2.8.0` installed? You might need to upgrade your `pydantic-core` version. Lmk how that works for you!

**Comment by sydney-runkle** [comment]
Also, I'm guessing we don't need the `coverage.yml` file assuming the added step in `ci.yml` works?

**Comment by sydney-runkle** [comment]
Closing in favor of https://github.com/pydantic/pydantic/pull/9833, great work here!

**Comment by AlessandroMiola** [comment]
> Also, I'm guessing we don't need the `coverage.yml` file assuming the added step in `ci.yml` works?

Hi @sydney-runkle, the two files approach should be the way to go (according to the docs at https://github.com/py-cov-action/python-coverage-comment-action?tab=readme-ov-file#basic-usage)

> for cases where you expect PRs from users that don't have write access to the repository

Btw, I saw you kept the approach on the new PR :)

**Pull request closed without merging**
