### PR TITLE
Logo grid for pydantic users

### PR DESCRIPTION
**Pull request by tpdorsey**
Replaces the bullet list of companies using pydantic with a grid of logos.

TODO: 
- expand the grid with more logos!
- improve dark mode rendering

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @samuelcolvin

### CODE REVIEW

**Comment by tpdorsey** [comment]
please review

**Review by samuelcolvin — COMMENTED** [review]
Looking good, lets:
* remove the section of bullet points above this
* add FastAPI and Jupyter to the list of logos

**Comment by samuelcolvin** [comment]
please update.

**Comment by samuelcolvin** [comment]
I think long term, the logos should get smaller, and we should have more of them, but that can happen later.

**Comment by tpdorsey** [comment]
please review

**Comment by samuelcolvin** [comment]
Screenshot 2023-05-26 at 22 41 26

Some logos aren't showing, also some don't show well in dark mode - I guess we can just change those colors to black.

We'll need to make each logo into a link in future, but for now, can we just set the title on each image to the company name?

Please update.

**Comment by tpdorsey** [comment]
@samuelcolvin what do we want them to link to? I think the logos are fine unless we have some CTA at the other end of the link

**Comment by samuelcolvin** [comment]
I think we need a page (doesn't need to be in a menu) with heading for each of these companies, and one sentence on how we know they're using pydantic and how they're using us.

Also need to add:
* nasa
* nvidia
* IPCC - international panel on climate change
* JP Morgan
* Twitter

**Comment by tpdorsey** [comment]
please review

**Comment by tpdorsey** [comment]
I will add the links and supplemental information about each logo as a separate pr

**Review by samuelcolvin — APPROVED** [review]
great, thank you.

**Pull request merged**
