### PR TITLE
Fix parent namespace issue with model rebuilds

### PR DESCRIPTION
**Pull request by sydney-runkle**
WIP, not going to move forward with the current solution, but wanted to sketch out what the problem was.

I think the best way forward here would be to further document what our internal namespace logic is doing, and separate out the different namespace fetching / caching logical paths.

Closes https://github.com/pydantic/pydantic/issues/10253

### CODE REVIEW

**Comment by sydney-runkle** [comment]
Hmm, concerned that memory usage is back up on `main`:

```
📏 Total allocations:
        3105763

📦 Total memory allocated:
        9.069GB

📊 Histogram of allocation size:
        min: 1.000B
        ---------------------------------------------
        < 4.000B   : 307851 ▇▇▇▇▇▇▇▇▇▇▇▇
        < 16.000B  : 615800 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 70.000B  : 457813 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 288.000B : 525727 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 1.163KB  : 663829 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 4.795KB  : 404699 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 19.771KB :  71428 ▇▇▇
        < 81.511KB :  31469 ▇▇
        < 336.054KB:  26759 ▇▇
        <=1.353MB  :    388 ▇
        ---------------------------------------------
        max: 1.353MB

📂 Allocator type distribution:
         MALLOC: 2939726
         REALLOC: 133924
         CALLOC: 31731
         MMAP: 382

🥇 Top 5 largest allocating locations (by size):
        - <dictcomp>:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:185 -> 4.038GB
        - add_module_globals:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:225 -> 2.028GB
        - push:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_generate_schema.py:339 -> 1.013GB
        - validate_core_schema:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_core_utils.py:570 -> 902.436MB
        - __init__:/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/typing.py:668 -> 352.625MB

🥇 Top 5 largest allocating locations (by number of allocations):
        - create_schema_validator:/Users/programming/pydantic_work/pydantic/pydantic/plugin/_schema_validator.py:50 -> 1119542
        - validate_core_schema:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_core_utils.py:570 -> 923652
        - complete_model_class:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:595 -> 478021
        - <dictcomp>:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:185 -> 124646
        - __init__:/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/typing.py:668 -> 91981
```

**Comment by sydney-runkle** [comment]
Currently, much worse on this branch, so need to fix that:

```py
📏 Total allocations:
        3297710

📦 Total memory allocated:
        19.165GB

📊 Histogram of allocation size:
        min: 1.000B
        ---------------------------------------------
        < 4.000B   : 307851 ▇▇▇▇▇▇▇▇▇▇▇
        < 16.000B  : 615800 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 70.000B  : 457813 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 288.000B : 525729 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 1.163KB  : 707992 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 4.795KB  : 448390 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 19.771KB : 114182 ▇▇▇▇▇
        < 81.511KB :  69305 ▇▇▇
        < 336.054KB:  46130 ▇▇
        <=1.353MB  :   4518 ▇
        ---------------------------------------------
        max: 1.353MB

📂 Allocator type distribution:
         MALLOC: 3127272
         REALLOC: 134058
         CALLOC: 31869
         MMAP: 4511

🥇 Top 5 largest allocating locations (by size):
        - <dictcomp>:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:185 -> 6.058GB
        - __init__:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:683 -> 2.540GB
        - add_module_globals:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:232 -> 2.028GB
        - unpack_lenient_weakvaluedict:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:725 -> 2.019GB
        - build_lenient_weakvaluedict:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:711 -> 2.019GB

🥇 Top 5 largest allocating locations (by number of allocations):
        - create_schema_validator:/Users/programming/pydantic_work/pydantic/pydantic/plugin/_schema_validator.py:50 -> 1119540
        - validate_core_schema:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_core_utils.py:570 -> 923664
        - complete_model_class:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:595 -> 478020
        - <dictcomp>:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:185 -> 186970
        - __init__:/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/typing.py:668 -> 92002
```

This definitely isn't going down the logical path that I want it to at the moment.

**Comment by sydney-runkle** [comment]
I've also opened https://github.com/pydantic/pydantic/pull/10260 to fix an issue that was causing memory blowup.

**Review by samuelcolvin — APPROVED** [review]
LGTM

**Pull request merged**
