### PR TITLE
Add ability to decorate descriptors

### LINKED ISSUE #5329: `@validate_arguments` gives a confusing error if put above @classmethod
```python
from pydantic import validate_arguments

class MyClass:
    @validate_arguments
    @classmethod
    def my_classmethod(cls, x: int):
        return x
```
```
TypeError: <classmethod(<function MyClass.my_classmethod at 0x104c005e0>)> is not a callable object
```
I know we've discussed making other improvements to the `@validate_arguments` decorator, but felt like it probably made sense to create a tracking issue for this. It seems to me like it should be perfectly possible to resolve this, or at least produce a better error saying to re-order the decorators.

The original source of this issue: https://github.com/pydantic/pydantic/issues/1205#issuecomment-1492668119

Selected Assignee: @samuelcolvin

### PR DESCRIPTION
**Pull request by malikoth**
## Change Summary
Adds a(nother) wrapper layer that can wrap descriptors.

## Related issue number
Fix #5329

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by malikoth** [comment]
I'm writing this on Windows at the moment, and `memray` doesn't support a win32 target, so I cannot install a virtualenv or run the tests on this machine. I'll try it on my Mac later.

I can make progress on getting this to a point of being mergeable as per the checklist above, but before I put in all the effort, I'd love to see some discussion on the issue this fixes, which doesn't have any comments whatsoever, and also a general comment on this PR indicating if this solution is on the right track to being acceptable.

**Comment by adriangb** [comment]
The main problem is that you're trying to fix Pydantic V1, which [is not actively developed anymore](https://docs.pydantic.dev/latest/version-compatibility/#pydantic-v1-support). I'd encourage you to try to re-target Pydantic V2 if the problem still exists in V2.

**Comment by malikoth** [comment]
Took me some digging to finally realize that the decorator was renamed from `validate_arguments` to `validate_call`. lol  Well, I've confirmed that the original (mis)behavior still exists on `validate_call` in 2.0, so I'll submit another attempt at a patch for that as soon as I can. Thank you for your patience!

**Comment by samuelcolvin** [comment]
Closing this, please create a new project if you think `validate_call` needs work.

**Pull request closed without merging**
