### PR TITLE
Fix deduplication of Enum refs in CoreSchema

### LINKED ISSUE #6270: Duplicate ref with multiple optional Enums inside a pydantic dataclass
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When using `pydantic.dataclasses.dataclass`, I noticed a data constellation which cannot be built (see the example code):
Multiple fields of the same optional enum type inside a single dataclass.

When trying to execute the example code, I am getting:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/simon/tmp/pydantic-reproducer/pydantic_reproducer.py", line 11, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Users/simon/tmp/pydantic-reproducer/.venv/lib/python3.11/site-packages/pydantic/dataclasses.py", line 210, in dataclass
    return create_dataclass(_cls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/tmp/pydantic-reproducer/.venv/lib/python3.11/site-packages/pydantic/dataclasses.py", line 201, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/tmp/pydantic-reproducer/.venv/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 155, in complete_dataclass
    cls.__pydantic_validator__ = validator = SchemaValidator(simplified_core_schema, core_config)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Error building "dataclass" validator:
  SchemaError: Error building "dataclass-args" validator:
  SchemaError: Field 'member_b':
  SchemaError: Error building "default" validator:
  SchemaError: Error building "nullable" validator:
  SchemaError: Duplicate ref: `__main__.MyEnum:140446243941536`
```

possibly related: #5660 

I have tried varying a few parameters. The error does **not** appear when...
- using `BaseModel` instead of `pydantic.dataclasses.dataclass`
- the Enum is a non-optional member
- using another dataclass instead of an Enum

### Example Code

```Python
from enum import Enum
from typing import Optional

from pydantic import Field, BaseModel
from pydantic.dataclasses import dataclass

class MyEnum(Enum):
    a = "a"
    b = "b"

@dataclass
class MyDataclass:
    member_a: Optional[MyEnum] = Field("a")
    member_b: Optional[MyEnum] = Field("b")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b3
        pydantic-core version: 0.41.0 release build profile
                 install path: /Users/simon/tmp/pydantic-reproducer/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #6270

Selected Reviewer: @samuelcolvin

### CODE REVIEW

**Comment by adriangb** [comment]
Needs a test added to https://github.com/pydantic/pydantic/blob/main/tests/test_internal.py

**Comment by adriangb** [comment]
please review

**Review by samuelcolvin — APPROVED** [review]
LGTM, I've added the test from the issue as a sanity check.

Probably worth @dmontagu reviewing as he did most of the work on refs.

**Comment by adriangb** [comment]
I wrote this ref stuff actually :)

**Pull request merged**
