### PR TITLE
fix: error in unique_items validator (#4626)

### LINKED ISSUE #4626: Not iterable error in optional lists constrained by unique items
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

`unique_items` validation breaks optional lists when `None` is passed as a value.

### Example Code

```Python
from typing import Any, Optional
from pydantic import BaseModel, conlist

class Model(BaseModel):
    prop: Optional[conlist(Any, unique_items=True)]

m = Model(prop=None)

#> pydantic.error_wrappers.ValidationError: 1 validation error for Model
#> prop
#>   'NoneType' object is not iterable (type=type_error)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.0.dev0
install path: C:\repos_me\ppp\pydantic\pydantic
python version: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.19044
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by nuno-andre**
Fixes #4626

### CODE REVIEW

**Comment by samuelcolvin** [comment]
As part of the move to V2, all of `pydantic/types.py` has been removed or changed, see #4516.

Therefore this change doesn't make sense.

Happy to consider adding it to pydantic-core if a good approach can be found https://github.com/pydantic/pydantic-core/issues/296

**Comment by nuno-andre** [comment]
@samuelcolvin Would it make sense to submit this PR to the `1.10.X-fixes` branch?

**Comment by samuelcolvin** [comment]
Are you sure this isn't fixed by #4568?

**Comment by nuno-andre** [comment]
> Are you sure this isn't fixed by #4568?

My bad! I didn't search for this fix.

**Pull request closed without merging**
