### PR TITLE
Remove contuple from types

### PR DESCRIPTION
**Pull request by hramezani**
It's not needed per discussion with @samuelcolvin 

Selected Reviewer: @samuelcolvin

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Review by dmontagu — APPROVED** [review]

**Comment by dmontagu** [comment]
I see @samuelcolvin was assigned but this seems fine considering this function didn't exist in v1 and you can use Annotated  directly to achieve the same results. I'll just merge it 👍

**Comment by hramezani** [comment]
> I see @samuelcolvin was assigned but this seems fine considering this function didn't exist in v1 and you can use Annotated directly to achieve the same results. I'll just merge it 👍

Yes, that's the reason. Thanks!

**Comment by ModischFabrications** [comment]
Sorry to necro, but I was searching exactly for this type and this is the only mention. Might be sensible to add a hint to the docs why tuples are excluded, I was expecting one after finding the ones for lists and sets.

**Pull request merged**
