### PR TITLE
Validator decorator field check. Closes #3215

### LINKED ISSUE #3215: Throw descriptive exception for incorrectly defined validator fields.
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/3129

<div type='discussions-op-text'>

<sup>Originally posted by **SunsetOrange** August 24, 2021</sup>
I had been trying to locate a bug in my code for an hour or so, which I eventually narrowed down to an incorrectly defined custom validator decorator. I had placed multiple field strings into the decorator call, inside a list rather than as multiple args.

My own mistake, but Pydantic had been throwing a very unhelpful exception stating that my model was not hashable.
The exception was pointing at the class definition line, not the validator decorator.

`Exception has occurred: TypeError unhashable type: 'list'`

This confused me greatly for a good while as I tried to find a possible location in the model and its super classes where a list was being used as a dictionary key. As this is a mistake that others could easily make (and I think I have made it in the past as well), it would be nice and helpful to output an exception that identifies the mistake and provides helpful feedback. Else wise, the source of the exception is difficult to identify.

I proposing that the following code be added to class_validators.py at line 75.
```
    elif not all([isinstance(field, str) for field in fields]):
        raise ConfigError(
            "validator fields should be passed as separate string args. Do not pass multiple fields as a list, etc. "
            "E.g. usage should be `@validator('<field_name_1>', '<field_name_2>', ...)` "
            "NOT `@validator(['<field_name_1>', '<field_name_2>', ...], ...)`"
        )
```
</div>

### PR DESCRIPTION
**Pull request by SunsetOrange**
## Change Summary
Pydantic will throw a much more descriptive exception message when the field values are incorrectly set in a validator decorator.
## Related issue number

fixes #3215

## Checklist
* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review.

### CODE REVIEW

**Comment by SunsetOrange** [comment]
please review

**Comment by samuelcolvin** [comment]
Thanks so much, I updated the code to match our code style.

**Comment by samuelcolvin** [comment]
thanks so much for this.

**Comment by SunsetOrange** [comment]
No, thank you.

**Pull request merged**
