### PR TITLE
Ftp and Websocket connection strings support

### PR DESCRIPTION
**Pull request by CherrySuryp**
* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review

Hi everyone! I often use WS and FTP strings, so I thought it would be handy to add their validation to Pydantic. I think it should be useful for use when validating configurations in Pydantic Settings and for type annotations

### CODE REVIEW

**Comment by CherrySuryp** [comment]
please review

**Comment by CherrySuryp** [comment]
Hello there! That's my first contribution to pydantic :)
As I understood from [Release Instructions](https://github.com/pydantic/pydantic/blob/main/release/README.md) - relnotes have to be manually added by maintainers. That's why one of the CI checks didn't passed. Correct me if I'm wrong, thanks!

**Comment by sydney-runkle** [comment]
Looks good! I think we might move these to `pydantic-extra-types` in V3, but I think it's fine to add them here for now.

**Review by sydney-runkle — APPROVED** [review]

**Comment by CherrySuryp** [comment]
Yeah, I think it fits in networking.py module well for now

**Pull request merged**
