### PR TITLE
Move `tools` module to `deprecated` namespace

### LINKED ISSUE #5350: What are we doing with `tools` in V2?
I suggest we move it to deprecated, and rely on `AnalysedType` for similar functionality.

Maybe we add some convenience functions to replace `parse_obj_as` etc.?

### PR DESCRIPTION
**Pull request by Kludex**
## Change Summary

Closes #5350

This PR moves `tools` module to the `deprecated` namespace.

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by Kludex** [comment]
please review

**Review by hramezani — APPROVED** [review]
LGTM 👍

**Comment by hramezani** [comment]
Don't we need a deprecation warning when someone imports `tools`?

**Comment by Kludex** [comment]
I'll include all deprecations together (the other modules on the deprecated namespace are without warnings as well).

**Pull request merged**
