### PR TITLE
[Docs] Fix ModuleNotFoundError in Pydantic Extra Types

### PR DESCRIPTION
**Pull request by kinuax**
## Change Summary

The Pydantic Extra Types docs have several examples to run in the browser but `ModuleNotFoundError: No module named 'pydantic_extra_types'` error is raised because `pydantic-extra-types` is not installed. An example with `Latitude`: https://docs.pydantic.dev/latest/api/pydantic_extra_types_coordinate/#pydantic_extra_types.coordinate.Latitude.

I have updated `add_mkdocs_run_deps` to include this dependency with its version. Documentation is built and served correctly. I have verified the `Latitude` example (and others) and its docstring runs as expected.

For the sake of consistency on the output, the corresponding script is updated as well at https://github.com/samuelcolvin/mkdocs-run-code/pull/6.

## Checklist

* [X] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [X] Tests pass on CI
* [X] Documentation reflects the changes where applicable
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by kinuax** [comment]
`typing-extensions` tests raise `NotImplementedError` due to a reason unknown to me.

**Comment by antoni-jamiolkowski** [comment]
> `typing-extensions` tests raise `NotImplementedError` due to a reason unknown to me.

These tests fail on the main as well. It should be fixed in the https://github.com/pydantic/pydantic/pull/9426

**Review by sydney-runkle — APPROVED** [review]
Looks great, thanks! We are working on a fix for the tests, and will merge this after that gets fixed.

**Comment by sydney-runkle** [comment]
@kinuax,

If you pull in the changes from `main`, tests should pass now :).

**Pull request merged**
