### PR TITLE
Fix type hint of `model_config`

### PR DESCRIPTION
**Pull request by Viicos**
## Change Summary

Related: https://github.com/pydantic/pydantic-settings/pull/97. Could it be possible for someone to try and see if they have the same issue (on VSCode) described in https://github.com/pydantic/pydantic-settings/pull/97 🙏? As I said, it seems this issue is inconsistent, and it might be pylance doing weird things.

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @davidhewitt

### CODE REVIEW

**Comment by Viicos** [comment]
Please review

**Comment by davidhewitt** [comment]
May not be necessary, see https://github.com/pydantic/pydantic-settings/pull/97#issuecomment-1618976851

**Comment by Viicos** [comment]
Fixed by rebasing indeed (https://github.com/pydantic/pydantic-settings/pull/97#issuecomment-1619878943), thanks @davidhewitt

**Comment by Kludex** [comment]
Thanks for coming back and closing the PR @Viicos 🙏

**Pull request closed without merging**
