### PR TITLE
🔨 Include `pydantic-extra-types` to integration tests

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

Include [Pydantic-extra-types](https://github.com/pydantic/pydantic-extra-types) to integration tests with the main branch

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @Kludex

### CODE REVIEW

**Comment by yezz123** [comment]
please review

**Review by Kludex — APPROVED** [review]
fyi @lig

**Comment by yezz123** [comment]
can we merge this @Kludex @lig ?

**Review by lig — APPROVED** [review]
👍🏻 looks good

**Pull request merged**
