### PR TITLE
Make requirements/rebuild.sh and requirements/refresh.sh executable

### PR DESCRIPTION
**Pull request by hramezani**
## Change Summary
Make requirements/rebuild.sh and requirements/refresh.sh executable and update dependencies
 

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @dmontagu

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Comment by adriangb** [comment]
Is this a refresh or a rebuild?

**Comment by hramezani** [comment]
> Is this a refresh or a rebuild?

rebuild

**Comment by adriangb** [comment]
I guess, why did we need to update all of the dependencies?

**Comment by hramezani** [comment]
> I guess, why did we need to update all of the dependencies?

it's not needed right now I think. 

Actually, I wanted to add `pydantic-core` to docs dependencies. Then I realized both `refresh.sh` and `rebuild.sh` are not executable when I run the `make rebuild-lockfiles`. So, I created this PR to make them executable and then `rebuild` all the dependencies. I will revert the update part.

BTW, Do you see any problem in updating dependencies?

**Comment by adriangb** [comment]
No problem per se but it's good to not update them unless there is a reason to to keep the diffs smaller, minimize env re-installs devs have to do, etc.. That's what most lockfile management systems do.

**Comment by hramezani** [comment]
@adriangb just reverted the dependencies update

**Review by adriangb — APPROVED** [review]

**Pull request merged**
