### PR TITLE
update links to https://github.com/pydantic/…

### LINKED ISSUE #4397: Update github.com/samuelcolvin links
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Some links were not updated, the automatic redirect failed me yesterday, updating the links is easy.

### Example Code

```Python
pydantic$ grep github.com/samuelcolvin/py . -R 
./docs/blog/pydantic-v2.md:Updated late 10 Jul 2022, see [pydantic#4226](https://github.com/samuelcolvin/pydantic/pull/4226).
./docs/blog/pydantic-v2.md:[pydantic-core](https://github.com/samuelcolvin/pydantic-core) which I've been building over the last few months.
./docs/blog/pydantic-v2.md:[see a list here](https://github.com/samuelcolvin/pydantic-core/blob/main/pydantic_core/_types.py#L291).
./docs/blog/pydantic-v2.md:See [pydantic-core#153](https://github.com/samuelcolvin/pydantic-core/issues/153)
./docs/blog/pydantic-v2.md:Looking at the pydantic-core [benchmarks](https://github.com/samuelcolvin/pydantic-core/tree/main/tests/benchmarks)
./docs/blog/pydantic-v2.md:like this for a long time, see [pydantic#1984](https://github.com/samuelcolvin/pydantic/issues/1984), but couldn't
./docs/blog/pydantic-v2.md:See [pydantic#1549](https://github.com/samuelcolvin/pydantic/issues/1549) for motivation.
./docs/blog/pydantic-v2.md:see [pydantic#1001](https://github.com/samuelcolvin/pydantic/issues/1001). This would avoid confusing gotchas when field
./docs/blog/pydantic-v2.md:[set of error codes and messages](https://github.com/samuelcolvin/pydantic-core/blob/main/src/errors/kinds.rs).
./docs/blog/pydantic-v2.md:  (pydantic-core is [already](https://github.com/samuelcolvin/pydantic-core/runs/7214195252?check_suite_focus=true)
./docs/blog/pydantic-v2.md:see [pydantic-core#154](https://github.com/samuelcolvin/pydantic-core/issues/154).
./docs/blog/pydantic-v2.md:[`pydantic_core.Schema`](https://github.com/samuelcolvin/pydantic-core/blob/main/pydantic_core/_types.py#L291)
./docs/blog/pydantic-v2.md:   [pydantic#784](https://github.com/samuelcolvin/pydantic/issues/784)
./docs/blog/pydantic-v2.md:   [pydantic-core#151](https://github.com/samuelcolvin/pydantic-core/issues/151)
./docs/blog/pydantic-v2.md:    see [pydantic-core#155](https://github.com/samuelcolvin/pydantic-core/issues/155)
./docs/blog/pydantic-v2.md:[discussions on github](https://github.com/samuelcolvin/pydantic/discussions/categories/pydantic-v2) - please
./docs/blog/pydantic-v2.md:    see [pydantic-core#152](https://github.com/samuelcolvin/pydantic-core/issues/152).
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: False
                 install path: /tmp/pydantic
               python version: 3.9.7 (default, Jun 22 2022, 20:11:26)  [GCC 11.2.0]
                     platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.34
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by commonism**
## Change Summary

update the links from github.com/samuelcolvin to github.com/pydantic

## Related issue number

fix #4397

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/pydantic/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

please review

skip change file check

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Weird, redirects seem to work fine for me, still may as well update.

**Comment by samuelcolvin** [comment]
Weird, redirects seem to work fine for me, still may as well update.

**Comment by commonism** [comment]
Yesterday I was referred to samuelcolvin.github.io/ - 404.

**Comment by samuelcolvin** [comment]
That's a different issue, fixed in https://github.com/pydantic/pydantic-core/commit/7bdee444e4e27d290128852af0aeef030b2bd651.

**Comment by samuelcolvin** [comment]
Thanks so much, I'll try to cherry-pick this only the 1.9 branch to update docs later.

**Pull request merged**
