### PR TITLE
add field_serializer to computed_field

### PR DESCRIPTION
**Pull request by andresliszt**
This PR tries to add `field_seralizer` into computed fields described in #6964 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [X] Unit tests for the changes exist
* [X] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by andresliszt** [comment]
Updating unit tests

**Comment by andresliszt** [comment]
please review

**Comment by adriangb** [comment]
This looks good @andresliszt ! Can you add a test using `Annotated[..., PlainSerializer()]` as the return type from a computed field function?

**Comment by andresliszt** [comment]
> This looks good @andresliszt ! Can you add a test using `Annotated[..., PlainSerializer()]` as the return type from a computed field function?

done!, is that what you wanted? Thanks for the observation

**Review by adriangb — APPROVED** [review]

**Pull request merged**
