### PR TITLE
Refactor documentation

### PR DESCRIPTION
**Pull request by Kludex**
🚧  WIP

- Related to https://github.com/pydantic/pydantic/issues/7322

## Checklist

- [ ] Remember to check if all redirect links are included on the `mkdocs.yml`. See how to do it on https://github.com/pydantic/pydantic/blob/3b297adf6132636646f36e77a5cd2aacd6b4f03b/mkdocs.yml#L211-L212.

> [!Note]
> Should we really squash this?

### CODE REVIEW

**Review by samuelcolvin — APPROVED** [review]
LGTM.

**Review by samuelcolvin — CHANGES_REQUESTED** [review]
There are still some links to usage:

```
pydantic/types.py
1541:    'See https://pydantic-docs.helpmanual.io/usage/types/extra_types/payment_cards/.',

pydantic/color.py
11:    See [`pydantic-extra-types.Color`](../usage/types/extra_types/color_types.md)
73:    'See https://pydantic-docs.helpmanual.io/usage/types/extra_types/color_types/.',

pydantic/_internal/_generate_schema.py
253:            f'`json_encoders` is deprecated. See https://docs.pydantic.dev/{version_short()}/usage/serialization/#custom-serializers for alternatives',

docs/plugins/main.py
235:    if page.file.src_uri != 'usage/schema.md':
265:    if page.file.src_uri != 'usage/conversion_table.md':

docs/blog/pydantic-v2.md
647:[`__get_validators__`](https://docs.pydantic.dev/usage/types/#classes-with-__get_validators__)
754:7. [Settings Management](https://docs.pydantic.dev/usage/settings/) ??? - I definitely don't want to
```

**Comment by samuelcolvin** [comment]
We should move "API documentation" up/left to just after concepts.

**Comment by RitikShah** [comment]
I found this documentation system a while back that might be useful for this: https://documentation.divio.com/

it's a bit overwhelming, so I've generally cherry picked ideas, but I love the concept overall.

**Comment by samuelcolvin** [comment]
Merging this, we can work on more stuff, from main.

Still to do: 
* move more stuff from concepts to API docs
* check all old pages have redirects

**Review by samuelcolvin — APPROVED** [review]

**Pull request merged**
