### PR TITLE
Use __pydantic_serializer__ for serializing Any fields

### PR DESCRIPTION
**Pull request by dmontagu**
Won't work until https://github.com/pydantic/pydantic-core/pull/557 is merged and released, but opening this for now.

Selected Reviewer: @Kludex

### CODE REVIEW

**Comment by dmontagu** [comment]
(Now that the pydantic core PR was merged, this test should pass as soon as we start using a new release of pydantic core in pydantic; when that happens, merging main into this PR should make the test pass.)

**Comment by dmontagu** [comment]
please review

**Comment by hramezani** [comment]
There are some Failing CI
Please update

**Comment by dmontagu** [comment]
This should be resolved/merge-able once a new version of pydantic core is released and in use in pydantic, I don't think there is anything to do until then.

**Pull request merged**
