### PR TITLE
chore(feat): Add `MySQL` & `MariaDB` to Pydantic types

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

Support `MySQL` & `MariaDB` as we have `PostgreSQL` and other wonderful connectors we can also add support for these too, as the wide use of both of them and some sync/async connectors ex:

- [`mysql+mysqldb`](https://pypi.org/project/mysqlclient/)
- [`mysql+pymysql`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.pymysql)
- [`mariadb+pymysql`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mariadbconnector)
- [`mysql+mysqlconnector`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqlconnector)
- [`mysql+asyncmy`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.asyncmy)
- [`mysql+aiomysql`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.aiomysql)
- [`mysql+cymysql`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.cymysql)
- [`mysql+pyodbc`](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.pyodbc)

## Checklist
* [x]  Unit tests for the changes exist
* [x]  Tests pass on CI and coverage remains at 100%
* [x]  Documentation reflects the changes where applicable
* [x]  `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x]  My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Would be useful to have a source for all these. Both here and in the docs.

**Comment by yezz123** [comment]
> Would be useful to have a source for all these. Both here and in the docs.

Do you mean the source of each connector?

**Comment by yezz123** [comment]
please review

**Comment by yezz123** [comment]
My sense here is the same for example we use this function to setup `PostgreSQL` we can do the same for `MySQL` & `MariaDB` 

```py
from pydantic import BaseSettings, PostgresDsn


class DefaultSettings(BaseSettings):
    postgres_dealect_driver: str
    postgres_user: str
    postgres_password: str
    postgres_host: str
    postgres_db: str

    @property
    def db_url(self):
        return PostgresDsn.build(
            scheme=self.postgres_dealect_driver,
            user=self.postgres_user,
            password=self.postgres_password,
            host=self.postgres_host,
            path=f"/{self.postgres_db or ''}",
        )
```

- with `MySQL` or `MariaDB`:

```py
from pydantic import BaseSettings, MySQLDsn


class DefaultSettings(BaseSettings):
    mysql_dealect_driver: str
    mysql_user: str
    mysql_password: str
    mysql_host: str
    mysql_db: str

    @property
    def db_url(self):
        return MySQLDsn.build(
            scheme=self.mysql_dealect_driver,
            user=self.mysql_user,
            password=self.mysql_password,
            host=self.mysql_host,
            path=f"/{self.mysql_db or ''}",
        )
```

**Comment by samuelcolvin** [comment]
> Do you mean the source of each connector?

I mean some sort of link to the docs of the databases saying "these are the possible DSN schemes", ideally an authoritative source. But if it's not possible, don't worry.

**Comment by yezz123** [comment]
> > Do you mean the source of each connector?
> 
> I mean some sort of link to the docs of the databases saying "these are the possible DSN schemes", ideally an authoritative source. But if it's not possible, don't worry.

got it, yes here is the one we base on it for the configuration of MySQL https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
Thanks @yezz123 for this.

LGTM :+1:

**Comment by samuelcolvin** [comment]
> got it, yes here is the one we base on it for the configuration of MySQL https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html

Humm, looking into this more, it seems most of the connection schemes (e.g. `mysql+aiomysql`) relate specifically to sqlalchemy, hence the link you already have in the body is all there is.

Happy to accept this as is.

**Pull request merged**
