### PR TITLE
fix(validator): impl signature for reuse validator

### LINKED ISSUE #3407: Reuse validator: signature cannot be determined
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/.../.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep  9 2021, 23:20:13)  [GCC 9.3.0]
                     platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
...
```

Hi all,

I have to validate one particular field in many classes. As encouraged [in the docs](https://pydantic-docs.helpmanual.io/usage/validators/#reuse-validators), I have extracted this into a help function, which works perfectly.

The bug (?) I'd like to report concerns the signature of the validator, which cannot be determined by `inspect.signature`.
If you are wondering, the signature is read by [sphinx autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) in the process of generating the API documentation.

Here's a MWE showing the problem:

```py
import inspect

from pydantic import validator


@validator('field')
def check_function(value: int) -> int:
    return value

inspect.signature(check_function)
```

This snippet returns:

```py
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "/usr/lib/python3.9/inspect.py", line 3111, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.9/inspect.py", line 2860, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.9/inspect.py", line 2259, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <classmethod object at 0x7f8821541730> is not a callable object
```

### PR DESCRIPTION
**Pull request by JeanArhancet**
## Related issue number

fix #3407 
## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by JeanArhancet** [comment]
I am currently stuck on the mypy errors, if anyone can support me

Please review

**Comment by samuelcolvin** [comment]
@JeanArhancet not sure what's going on here, could you rebase or merge with master to get tests to work.

Please update.

**Comment by JeanArhancet** [comment]
I have just rebased @samuelcolvin 

Please review

**Comment by samuelcolvin** [comment]
This is failing, please update.

I have a lot of PRs to go through, please try to get the PR to the point where it's finished and ready for review before assigning me.

**Pull request closed without merging**
