### PR TITLE
Fix `validate_call` schema generation and doc error for `TypedDict`

### PR DESCRIPTION
**Pull request by adriangb**
Fixes https://github.com/pydantic/pydantic/issues/6356

Selected Reviewer: @lig

### CODE REVIEW

**Comment by adriangb** [comment]
please review

**Review by Kludex — CHANGES_REQUESTED** [review]
Can we add a test with a TypedDict on the signature or a BaseModel based class or both?

**Comment by Kludex** [comment]
About the confusion that I did on the version being 3.11: there's a comment on the standard library that I believe is not correct about this - this is a comment to remind me to check this when I get home.

**Comment by adriangb** [comment]
I'm sure _we_ need 3.12+ because of https://github.com/python/cpython/pull/103698

**Comment by adriangb** [comment]
@Kludex added a test and fixes some other bugs with `validate_call`

**Comment by adriangb** [comment]
please review

**Review by Kludex — APPROVED** [review]
Thanks 😁🙏

**Pull request merged**
