### PR TITLE
Add support for `collections.abc.Collection` and `typing.Collection` types

### PR DESCRIPTION
**Pull request by sydney-runkle**
Fix https://github.com/pydantic/pydantic/issues/9899

### CODE REVIEW

**Review by dmontagu — COMMENTED** [review]
Can you confirm whether this has any impact on the handling of user-defined subclasses of `collections.abc.Collection` used as annotations when arbitrary types are allowed? I'm concerned this may cause them to be validated into lists rather than being kept as they are. I wouldn't necessarily have a problem with that if it always worked that way, but I'm concerned it may be a breaking change for some existing usage.

**Comment by sydney-runkle** [comment]
Sure thing. On `main`:

```py
from collections.abc import Collection

from pydantic import BaseModel, ConfigDict

class MyCollection(Collection):
    def __init__(self, initial_items):
        self._items = list(initial_items)
    
    def __len__(self):
        return len(self._items)
    
    def __iter__(self):
        return iter(self._items)
    
    def __contains__(self, item):
        return item in self._items

class Test(BaseModel):
    collection: Collection[int]

    model_config = ConfigDict(arbitrary_types_allowed=True)

t = Test(collection=MyCollection([1, 2, 3]))
print(repr(t))
#> Test(collection=<__main__.MyCollection object at 0x104e93370>)

model_data = t.model_dump()
print(t.model_dump())
#> {'collection': <__main__.MyCollection object at 0x1007b3430>}
```

On this branch, with my new changes:

```py
from collections.abc import Collection

from pydantic import BaseModel, ConfigDict

class MyCollection(Collection):
    def __init__(self, initial_items):
        self._items = list(initial_items)
    
    def __len__(self):
        return len(self._items)
    
    def __iter__(self):
        return iter(self._items)
    
    def __contains__(self, item):
        return item in self._items

class Test(BaseModel):
    collection: Collection[int]

    # model_config = ConfigDict(arbitrary_types_allowed=True)

t = Test(collection=MyCollection([1, 2, 3]))
print(repr(t))
#> Test(collection=<__main__.MyCollection object at 0x104e93370>)

model_data = t.model_dump()
print(t.model_dump())
#> {'collection': [1, 2, 3]}
```

**Comment by sydney-runkle** [comment]
They're still validated into collections due to the isinstance schemas :)

**Comment by sydney-runkle** [comment]
Ah this is actually more complicated than I thought - we need to support dicts as well. Will finish this up tomorrow.

**Comment by sydney-runkle** [comment]
Going to close this - this isn't the right approach - we need to create a collection validator separately, but it's going to be hard to maintain + design. I wouldn't say this is high priority right now.

**Pull request closed without merging**
