### PR TITLE
Don't apply dataclass transform twice with plugin + mypy 1.1.1 (#5162)

### LINKED ISSUE #5161: mypy error "Unexpected keyword argument" on pydantic dataclass InitVar field
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Since upgrading to pydantic 1.10.6, mypy started complaining about a kwarg being passed to the constructor of a dataclass if the field is an `InitVar`.

I'm guessing it might be related to https://github.com/pydantic/pydantic/pull/5111

```
$ mypy test.py
test.py:10: error: Unexpected keyword argument "foo" for "MyDataclass"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

### Example Code

```Python
from pydantic.dataclasses import dataclass
from dataclasses import InitVar

@dataclass
class MyDataclass:
    foo: InitVar[str]
    bar: str

MyDataclass(foo="foo", bar="bar")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.6
            pydantic compiled: True
                 install path: /home/brian/repos/medigator/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
                     platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.29
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by cdce8p**
(cherry picked from commit 355e6dac6b1881a12cf48783f42dd8a3991437b2)

## Change Summary
Cherry picked fix from `1.10.X-fixes` branch (#5162) onto `main`.
/CC: @dmontagu 

Closes #5161

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by samuelcolvin** [comment]
please update (just so we know who's assigned).

**Comment by cdce8p** [comment]
Seems like `InitVar` causes the crash with pydantic `v2` and mypy. Not sure why

**Comment by dmontagu** [comment]
It seems to me that the inclusion of `InitVar` on any dataclass is causing `get_class_decorator_hook` to get called infinitely.

I'm thinking either this affects all dataclass-oriented mypy plugins, or there is something funny going on with how we've defined our dataclasses.

Marshmallow has a dataclasses plugin that I think we could use as a reference to see if they have issues handling `InitVar` with the same versions of mypy/etc. If so, I think it will be easier for us to go to the mypy devs (and/or dataclasses devs?) and explain that this seems broken; if not, hopefully that will give us some more insight into what could be going wrong.

However, before digging into this more deeply, I'd like to wait for @samuelcolvin's work on v2 dataclasses to come through in the case that it ends up having any effect on the mypy side of things. (I suspect this is unlikely as it seems current work is mostly focused on the `pydantic_core` side of things, but, stil..)

**Comment by dmontagu** [comment]
Update: I did a bit more digging, and noticed that there must be something more complicated going on; a much simpler file that can reproduce the infinite calling to the dataclass transform decorator:

```python
from dataclasses import InitVar  # noqa E402

from pydantic import BaseModel, ConfigDict
from pydantic.dataclasses import dataclass


class Model(BaseModel):
    x: float
    y: str

    model_config = ConfigDict(from_attributes=True)

    not_config = ConfigDict(frozen=True)  # <--------- this line


@dataclass
class MyDataClass:
    foo: InitVar[str]
    bar: str
```

Very interestingly, if I delete the line with the `# <--------- this line` comment above, the issue goes away(!). I'll do a bit more investigation now given this is a pretty promising lead.

**Comment by dmontagu** [comment]
Okay, I think this is good to merge. The main change I made is dropping the analysis of non-annotated fields.

I'm not sure why that was causing infinite loops but it's no longer valid in v2 anyway, so I dropped it as a config option and made it always error and stop analyzing further. That seems to have resolved the issue.

@samuelcolvin If you are okay with the docs changes (presumably we'll do a bigger pass eventually, but I wanted to update this now so I don't forget), and with the high-level ideas behind the changes, then I think this is good to merge.

**Comment by dmontagu** [comment]
please review

**Review by samuelcolvin — COMMENTED** [review]
LGTM, although i haven't read every line.

**Pull request merged**
