### PR TITLE
Add `len` to `_BaseUrl` to avoid TypeError

### LINKED ISSUE #11092: AnyUrl: TypeError: object of type 'AnyUrl' has no len()
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

I have noticed that when using **AnyUrl** with **Field** **max_length** it returns:
```
Traceback (most recent call last):
  File "/Users/XXXX/XXX/XXXXX/.venv/lib/python3.12/site-packages/pydantic/_internal/_validators.py", line 324, in max_length_validator
    if len(x) > max_length:
       ^^^^^^
TypeError: object of type 'AnyUrl' has no len()
```

I'm aware that more Pydantic way would be to use `UrlConstrains` with max_length. However before introducing _BaseUrl and its custom schema (so in **Pydantic 2.9.2**), it was working and I notice that had been used in some libraries. 

I tried if simple adding a magic method __len__ to _BaseUrl would solve the issue and it worked. However I'm not sure if this would be the best solution (quite new to internals of Pydantic).
```python
def __len__(self) -> int:
    return len(str(self._url))
```

So to sum up, code below worked without an issue in Pydantic 2.9.2, however in Pydantic 2.10.x the same code raises TypeError.

### Example Code

```Python
from pydantic import AnyUrl, Field, BaseModel


class SomeClass(BaseModel):
    url: AnyUrl = Field(max_length=100)


SomeClass(url="https://example.com")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
pydantic-core version: 2.27.1
pydantic-core build: profile=release pgo=false
install path: /Users/XXXXX/XXXX/XXXXXX/.venv/lib/python3.12/site-packages/pydantic
python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
platform: macOS-14.6.1-arm64-arm-64bit
related packages: typing_extensions-4.12.2
commit: unknown
```

### PR DESCRIPTION
**Pull request by Kharianne**
## Change Summary

Add magic method to _BaseUrl class to support allowed usage of Field with max length with AnyUrl and simple length comparison and checks of AnyUrl types.

## Related issue number
fix #11092 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by Kharianne** [comment]
please review

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Thanks!

I think we can just to `len(self._url)` in the `__len__` check.

Could you also please add this fix to `_BaseMultiHostUrl` and add a test for that as well?

We'll get this into our patch release tomorrow :)

**Comment by Kharianne** [comment]
@sydney-runkle 

No problem! :-) 
However your proposal does not work: 
`len(self._url)` --> `'pydantic_core._pydantic_core.Url' has no len() ` 
That's why I needed to add the extra step to call the str method defined on _BaseUrl.

The self._url is a type Url from pydantic-core and this class is not of type Sized - not having __len__. Maybe this should be fixed in pydantic-core?

**Comment by sydney-runkle** [comment]
Hmm yeah, this makes sense I guess, we used to be able to apply directly to the core schema, and now we have this complex wrapped type.

**Review by sydney-runkle — APPROVED** [review]
Thanks for the tests! Looks good for now.

We can move the `__len__` support to `pydantic-core` eventually...

**Pull request merged**
