### PR TITLE
✅ Add tests illustrating #5597

### PR DESCRIPTION
**Pull request by lig**
## Change Summary

Add tests illustrating `Sequence[int]` behavior when using with json. 

## Related issue number

See #5597

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
is this still needed? If so please update.

**Comment by lig** [comment]
One test has been copied to #5706. Other two are still relevant after the rebase.

**Comment by dmontagu** [comment]
@lig I only see one test left here, and as currently written, I don't think it makes sense:

```python
def test_validate_json_raises_if_json_schema_raises():
    class Model(BaseModel):
        int_seq: Sequence[int]

    with pytest.raises(PydanticInvalidForJsonSchema) as e_json_schema:
        Model.model_json_schema()
    with pytest.raises(PydanticInvalidForJsonSchema) as e_validate_json:
        Model.model_validate_json('{}')

    assert e_json_schema.value.errors() == e_validate_json.value.errors()
```

`Model.model_json_schema()` would be capable of raising a `PydanticInvalidForJsonSchema` (though it no longer does in this specific case). But `Model.model_validate_json('{}')` would raise a `ValidationError`. In particular, I don't think there's any world where the json schema errors would be equal to the errors arising from attempted validation. So I'm not sure what this final test is trying to demonstrate.

**Comment by lig** [comment]
@dmontagu citing #5597 :

> Generating json schema via BaseModel.model_json_schema() raises PydanticInvalidForJsonSchema error which seems as a correct behavior.
> 
> However, calling BaseModel.validate_json(...) results in an attempt to validate passed json value while the validation schema is invalid.

So, It just doesn't make sense to me attempting to validate data using the schema that already has errors. What schema are we using for that?

**Comment by lig** [comment]
> (Also, we do now generate a valid JSON schema for this model, which I think is reasonable, so you won't get a PydanticInvalidForJsonSchema anyway)

Oh, I didn't notice that. I'll update the test.

**Comment by dmontagu** [comment]
> What schema are we using for that?

The pydantic core schema (available in `Model.__pydantic_core_schema__`). Technically, we use a slightly post-processed version of that schema during validation and serialization, as you can see here: 

https://github.com/pydantic/pydantic/blob/7df75059df9746a398a188553b88724e3df5c44f/pydantic/_internal/_model_construction.py#L204-L209

**Comment by lig** [comment]
Ok. Let's close this and #5597 then. It just a naming confusion, I guess.

**Pull request closed without merging**
