### PR TITLE
Add a test demonstrating how to integrate with a third-party type

### PR DESCRIPTION
**Pull request by dmontagu**
Inspired by https://github.com/pydantic/pydantic/issues/2316, I added a test demonstrating how third party types can be added. (We'll want to include similar documentation in the real docs, I have added a note to the documentation project about it linking to this PR.)

Selected Reviewer: @hramezani

### CODE REVIEW

**Review by Kludex — APPROVED** [review]
Should we include the JSON part as a "complete" example?

**Comment by dmontagu** [comment]
@Kludex do you just mean adding a call to `model_validate_json` with an assert, or something more complex?

**Comment by Kludex** [comment]
> @Kludex do you just mean adding a call to `model_validate_json` with an assert, or something more complex?

I mean being able to generate the json schema. I mean implementing `__get_pydantic_json_schema__`.

**Comment by dmontagu** [comment]
please review

(Also @Kludex I added the JSON schema)

**Review by Kludex — APPROVED** [review]

**Pull request merged**
