### PR TITLE
Check that Generic class has parameters before using it.

### LINKED ISSUE #10689: Cannot create dataclass inheriting from Generic
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    @pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/pydantic/dataclasses.py", line 224, in create_dataclass
    generic_base = Generic[cls.__parameters__]  # type: ignore
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "python3.11/typing.py", line 379, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "python3.11/typing.py", line 1848, in __class_getitem__
    raise TypeError(
TypeError: Parameter list to Generic[...] cannot be empty
```

### Example Code

```Python
import dataclasses
from typing import Generic, TypeVar

import pydantic

T = TypeVar('T')


@dataclasses.dataclass
class Base(Generic[T]):
  pass


@pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
class Derived(Base[int]):
  pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.7-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

### PR DESCRIPTION
**Pull request by jonathanasdf**
## Change Summary

See linked issue.

## Related issue number

fix #10689

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by jonathanasdf** [comment]
please review

**Comment by sydney-runkle** [comment]
Thanks for the PR. I fear this is actually a much bigger problem where we're not handling this correctly.

For example:

```py
import dataclasses
from typing import Generic, TypeVar

import pydantic

T = TypeVar('T')


@dataclasses.dataclass
class Base(Generic[T]):
  data: T


@pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
class Derived(Base[int]):
  pass

print(repr(Derived(data='not an int')))
#> data='not an int'
```

Occurs on this PR, which is not the desired behavior.

**Comment by jonathanasdf** [comment]
Fixing that issue would be far outside my comfort zone with the internals of how pydantic works. Would it make sense to merge this PR first, which at least fixes a hard crash, and create a separate issue for that one for some team member to fix later on?

**Comment by sydney-runkle** [comment]
I can take a look at this later today and see if it's fixable for the v2.10 release :).

**Comment by jonathanasdf** [comment]
Thank you very much!

**Comment by sydney-runkle** [comment]
I've pinged @dmontagu, let's see what he thinks re moving forward here.

**Comment by dmontagu** [comment]
Okay, so I can fix the issue @sydney-runkle pointed out with this patch:
```diff
diff --git a/pydantic/dataclasses.py b/pydantic/dataclasses.py
index db50ecf5a..ca6da33d7 100644
--- a/pydantic/dataclasses.py
+++ b/pydantic/dataclasses.py
@@ -8,7 +8,7 @@ import types
 from typing import TYPE_CHECKING, Any, Callable, Generic, NoReturn, TypeVar, overload
 from warnings import warn
 
-from typing_extensions import Literal, TypeGuard, dataclass_transform
+from typing_extensions import Literal, TypeGuard, dataclass_transform, get_type_hints
 
 from ._internal import _config, _decorators, _namespace_utils, _typing_extra
 from ._internal import _dataclasses as _pydantic_dataclasses
@@ -232,11 +232,29 @@ def dataclass(
             #   If the class is generic, we need to make sure the subclass also inherits from Generic
             #   with all the same parameters.
             bases = (cls,)
-            if issubclass(cls, Generic):
+            if issubclass(cls, Generic) and cls.__parameters__:
                 generic_base = Generic[cls.__parameters__]  # type: ignore
                 bases = bases + (generic_base,)
+
+            # Compute type hints with annotations that are aware of the parameterizations of the generic bases
+            cls_type_hints: dict[str, Any] | None = None
+            if hasattr(cls, '__orig_bases__'):
+                cls_type_hints = get_type_hints(cls)
+                cls_generic_mapping = {}
+                for orig_base in cls.__orig_bases__[::-1]:
+                    if hasattr(orig_base, '__origin__') and hasattr(orig_base.__origin__, '__parameters__') and hasattr(
+                        orig_base, '__args__'):
+                        for param, arg in zip(orig_base.__origin__.__parameters__, orig_base.__args__):
+                            cls_generic_mapping[param] = arg
+                for k in cls_type_hints:
+                    cls_type_hints[k] = cls_generic_mapping.get(cls_type_hints[k], cls_type_hints[k])
+
             cls = types.new_class(cls.__name__, bases)
 
+            # Use the generic-parametrized type hints if appropriate
+            if cls_type_hints:
+                cls.__annotations__ = cls_type_hints
+
         make_pydantic_fields_compatible(cls)
 
         # Respect frozen setting from dataclass constructor and fallback to config setting if not provided
```

However, that introduces some new bugs:
```python
import dataclasses
from typing import Generic, TypeVar

import pydantic

T = TypeVar('T')
S = TypeVar('S')


@dataclasses.dataclass
class Base1(Generic[T]):
    x: T


@dataclasses.dataclass
class Base2(Generic[T]):
    y: T


@pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
class Derived(Base1[int], Base2[str]):
    pass


Derived(x=1, y='y')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Derived
y
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='y', input_type=str]
"""
```
I think this is because my logic above for computing `cls_type_hints` (and in particular, updating it to reflect the generic parameters) isn't quite right. I'm not exactly sure what's wrong but it somehow needs to iterate over the base classes. In particular, the problem is that in that scenario, you get:
```python
...
class Derived(Base1[int], Base2[str]):
    pass
print(get_type_hints(Derived))
# {'y': ~T, 'x': ~T}
```
So it's already not clear from just looking at the type hints which class each T is coming from.

There could definitely be some better API for figuring out what the generic parameters should be in the type hints, but if there is, I'm not aware of it. But it does in principle feel to me that you should be able to collect this information by walking the hierarchy of (orig) base classes, and only updating fields with parameters from a given base class if the field itself is from that base class. Annoying but I think maybe not impossible. Won't surprise me if it ends up not perfectly matching python semantics, but I guess it would be close in most cases and we can always try to fix bugs when they are reported... ?

**Comment by jonathanasdf** [comment]
I never did understand how TypeVars in python should work. Does using `T` for both classes mean we intend for them to be instantiated with the same types? Should `Base2` be using `S` instead of `T`?

**Comment by sydney-runkle** [comment]
Closing for now in favor of https://github.com/pydantic/pydantic/pull/10723

**Comment by dmontagu** [comment]
It's due to a quirk in the way Python allows you to reuse a single TypeVar, in principle it should be equivalent whether you use the same value or not (and the type checker would treat it that way) but it's just not at runtime. I think with the recent changes in 3.12(?) to allow anonymous typevars, this is probably resolved, but I'm not 100% sure.

If you always use different typevars in different generics you wouldn't hit that issue but again, in principle you shouldn't have to. But I'm also not confident that's the only way things can go wrong with my snippet above...

**Pull request closed without merging**
