### PR TITLE
Fix bug with schema generation with Field(...) in a forward ref

### PR DESCRIPTION
**Pull request by dmontagu**
Closes https://github.com/pydantic/pydantic/issues/8485

### CODE REVIEW

**Review by sydney-runkle — APPROVED** [review]
This looks good to me. Thanks for the fix @dmontagu!

**Comment by sydney-runkle** [comment]
Let's wait to merge until @jsmith confirms that this fixes his issue 👍

**Comment by jsmith** [comment]
Thanks for the quick fix :) I'm out today but will confirm by Monday whether this fixes my issue (I'm almost 100% certain it does if the test is now passing).

**Comment by sydney-runkle** [comment]
@jsmith,

Sounds great. We'll go ahead and merge then. If it doesn't fix your original problem, we can address that as another issue / bug.

**Pull request merged**
