### PR TITLE
Add Codspeed profiling Actions workflow. 

### LINKED ISSUE #7961: Implement continuous profiling with `Codspeed`
We should use `Codspeed` for continuous profiling of things we care about like import time, as we do on `pydantic-core`.

See https://github.com/pydantic/pydantic/pull/7947#issuecomment-1783231475 for some more context.

We'd love some help on this 🙏!

### PR DESCRIPTION
**Pull request by lambertsbennett**
## Change Summary

I added a GitHub workflow to run Codspeed for Pydantic benchmarks. This is implemented in the same way as it is for pydantic-core and jiter. The only open question is whether to add a token for Codspeed. There is a token for jiter, but none for pydantic-core, so it wasn't entirely clear.

## Related issue number #7961

fix #7961 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

please review and decide on inclusion of the Codspeed token.

Selected Reviewer: @lig

### CODE REVIEW

**Comment by lambertsbennett** [comment]
please review

**Comment by lambertsbennett** [comment]
The Codspeed workflow fails with the error "Error: Unexpected status code: 401 {"error":"The repository is not enabled"}", so I think someone from the pydantic team needs to enable the repository on Codspeed.io.

**Comment by sydney-runkle** [comment]
@lambertsbennett,

Thanks a ton for your work on this. Looks great. We'll work on enabling `Codspeed` for the `pydantic` repo 👍 and get back to you soon 😄.

**Review by sydney-runkle — APPROVED** [review]
@lambertsbennett,

Looks great. Thanks for the contribution. Will merge this now 😄.

**Pull request merged**
