### PR TITLE
Fix config behavior with plain dataclass

### PR DESCRIPTION
**Pull request by sydney-runkle**
Fix https://github.com/pydantic/pydantic/issues/8693

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by sydney-runkle** [comment]
Please review

**Comment by davidhewitt** [comment]
Something seems strange here. We seem to have lots of tests in `test_dataclasses.py` which use config. Why are those passing?

**Comment by sydney-runkle** [comment]
@davidhewitt,

I believe it's because we're only testing validation focused settings, and the `__pydantic_config__` is pulled off of a class when schema is generated, see https://github.com/pydantic/pydantic/blob/02ee0f9fcc5ee5a70fe8a3d2e14f72834f21b065/pydantic/_internal/_generate_schema.py#L1231 for example.

**Comment by sydney-runkle** [comment]
That being said, I think we could clean this up a bit, I can create an issue for that.

**Comment by davidhewitt** [comment]
Right I see. So I don't think this is the right solution, because as you say the config is already pulled from the type into the schema.

I think actually if there's a bug, it's probably in core. See https://github.com/pydantic/pydantic-core/blob/e73b2d1edc5c3c062f1e0b381cda29d6ed6e5901/src/serializers/type_serializers/dataclass.rs#L83, where we do pull the config out of the schema to build a dataclass serializer. But why is that config not applying?

**Comment by sydney-runkle** [comment]
Good question. 30 mins of digging didn't help me much, but I'd be happy to look into this further in core. I still think that we might want this change though, as the schema serializer is what's used in accordance with the relevant settings here?

**Comment by davidhewitt** [comment]
I think that in all cases the schema should already contain the config fetched here; in effect doing this seems to me like it plasters over a core bug by sending the same config in twice. So I'd rather we wait to understand the interaction in core before considering this further.

**Comment by sydney-runkle** [comment]
Closing this, as I don't think this is the approach we want to take. Good to have as a reference for testing and such, though.

**Pull request closed without merging**
