### PR TITLE
Feat basesetting dev

### PR DESCRIPTION
**Pull request by oslijw**
Increase the number of data sources loaded from which variables in the setting are recorded through the log debug level

## Change Summary

I think that the loading of the configuration needs to add additional debug-level logging to facilitate the user to debug. For this reason, I specifically added the configuration loading source to the deep_update function in utils.py. At the same time, in order to be able to pass the instantiated Settings class, additional Added a variable, set it to None where it is not necessary to perform such an operation, and modified it in function-related positions

## Scope
pydantic/v1/utils->deep_update
pydantic/v1/env_settings/BaseSettings->_build_values
pydantic/v1/env_settings/EnvSettingsSource->__call__

## Related issue number
fix#5908 

## Checklist

* [ Y] Unit tests for the changes exist
* [ Y] Tests pass on CI and coverage remains at 100%
* [ Y] Documentation reflects the changes where applicable
* [ Y] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ Y] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by lig** [comment]
@oslijw As far as I can see your PR should be targeted to `main` branch but it is targeted to be merged into `1.10.X-fixes` branch. Would you mind changing the target branch of the PR to `main` instead of `1.10.X-fixes`, please?

**Comment by lig** [comment]
@oslijw Please, consider consulting Github Docs here: [Changing the base branch of a pull request - GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

**Comment by lig** [comment]
@oslijw Your changes are affecting `pydantic/v1` dir. This is just a copy of the latest `v1` release now encapsulated in the `main` branch to allow easier migration.

If you would like to change code in the `pydantic/v1` directory, you need to submit your changes as a patch to `1.10.X-fixes` branch and get wait for those changes to make it into the next Pydantic v1.10.x maintenance release. After the v1.10.x maintenance release is out its code will be introduced as an update for `pydantic/v1` package in the `main` branch.

Please, notice that changes that apply to `pydantic/v1` package in the `main` branch should be applied to `pydantic` package itself in the `1.10.X-fixes` branch.

**Comment by lig** [comment]
@oslijw If you have ideas or modifications intended for Pydantic v2, it is important to implement them in the appropriate location. I suggest implementing your ideas within the relevant files and directories specific to Pydantic v2. This way, your changes will be correctly applied to the new version.

The `pydantic/v1` packages is just a copy of the code released for Pydantic v1.10.x series.

You have two options:
1. Make modifications and test the code intended for Pydantic v2 release. This should be done in the `main` branch and should not affect `pydantic/v1` package.
2. Make modifications and test the code intended to fix a bug or unexpected behavior in Pydantic v1.10.x release. This should be done in the `1.10.X-fixes` branch.

**Comment by oslijunw** [comment]
v2 will remove deep_update and BaseSettings?

**Comment by lig** [comment]
I'm retargeting this PR to the `1.10.fixes` branch because the author made changes on top of that branch.

**Comment by lig** [comment]
@oslijw Another thing to mention. I see that you're trying to change Pydantic Settings part. This part is no longer part of the main Pydantic repo. If you would like to introduce you changes for v2 you need to look into https://github.com/pydantic/pydantic-settings/ repo and try to apply your changes there.

**Comment by oslijunw** [comment]
> @oslijw Another thing to mention. I see that you're trying to change Pydantic Settings part. This part is no longer part of the main Pydantic repo. If you would like to introduce you changes for v2 you need to look into https://github.com/pydantic/pydantic-settings/ repo and try to apply your changes there.

tks, I find the repo, I will submit a pr from that

**Comment by lig** [comment]
I'm closing this one then. Thank you!

**Pull request closed without merging**
