### PR TITLE
fix pattern matching version

### PR DESCRIPTION
**Pull request by samuelcolvin**
ref https://github.com/pydantic/pydantic/pull/3921#issuecomment-1217160250

skip change file check

### CODE REVIEW

**Comment by samuelcolvin** [comment]
please review.

**Review by Bobronium — APPROVED** [review]
LGTM! 😸

**Comment by irgolic** [comment]
Can't find a docs preview in CI, but conceptually LGTM

**Comment by samuelcolvin** [comment]
> Can't find a docs preview in CI, but conceptually LGTM
> 
> EDIT: Found it now that the rest of CI finished :) looks good

https://smokeshow.helpmanual.io/40174q1w4h6d071c084t/usage/models/#structural-pattern-matching

**Comment by Bobronium** [comment]
We also might want to automate some basic checks for minimal required version in examples.

Is there a known tool for that guesses minimal required version by checking for new syntax/other features?

Or, we can just run docs-build in matrix. There will be warnings on lower versions, but shouldn't be any errors.

**Comment by samuelcolvin** [comment]
> Or, we can just run docs-build in matrix. There will be warnings on lower versions, but shouldn't be any errors.

makes sense, but let's wait for V2 when I want to change the docs to build like watchfiles.

**Pull request merged**
