### PR TITLE
docs: Add documentation for Semantic Version and Timezone Name

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

@sydney-runkle I just released a new version in pydantic-extra once it's approved we can merge this. 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by sydney-runkle** [comment]
Looks good @yezz123, but could you please remove the `pdm.lock` diff?

**Comment by sydney-runkle** [comment]
Otherwise we can go ahead and merge, thanks!

**Comment by yezz123** [comment]
> Looks good @yezz123, but could you please remove the `pdm.lock` diff?

@sydney-runkle done 👍🏻

**Review by sydney-runkle — APPROVED** [review]
Thanks!

**Pull request merged**
