### PR TITLE
Option to exclude `model_extra` from `repr`

### LINKED ISSUE #9732: Option to exclude all `model_extras` from `repr`
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The [`model_config`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_config) attribute gives us the ability to `"allow"`, `"ignore"`, or `"forbid"` extra values, but I'd like to hide them similar to how `Field(..., repr=False)` can hide required/expected/known fields. My current approach overrides the models [`__repr_args__`](https://github.com/pydantic/pydantic/blob/c08dacdebc3a35a1a76ffbded593cab583e9f951/pydantic/main.py#L1024) method and excludes the logic around `pydantic_extra`:

```diff
    def __repr_args__(self) -> _repr.ReprArgs:
        for k, v in self.__dict__.items():
            field = self.model_fields.get(k)
            if field and field.repr:
                yield k, v

-       # `__pydantic_extra__` can fail to be set if the model is not yet fully initialized.
-       # This can happen if a `ValidationError` is raised during initialization and the instance's
-       # repr is generated as part of the exception handling. Therefore, we use `getattr` here
-       # with a fallback, even though the type hints indicate the attribute will always be present.
-       try:
-           pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
-       except AttributeError:
-           pydantic_extra = None
-
-       if pydantic_extra is not None:
-           yield from ((k, v) for k, v in pydantic_extra.items())
        yield from ((k, getattr(self, k)) for k, v in self.model_computed_fields.items() if v.repr)
```

But this seems hacky. I'd like to propose a new setting for the `model_config`, `"extra_repr"`, and wrap the `pydantic_extra` logic in `__repr_args__` with a conditional:

```diff
    def __repr_args__(self) -> _repr.ReprArgs:
        for k, v in self.__dict__.items():
            field = self.model_fields.get(k)
            if field and field.repr:
                yield k, v

+       if self.model_config.get("extra_repr", True):
+           # `__pydantic_extra__` can fail to be set if the model is not yet fully initialized.
+           # This can happen if a `ValidationError` is raised during initialization and the instance's
+           # repr is generated as part of the exception handling. Therefore, we use `getattr` here
+           # with a fallback, even though the type hints indicate the attribute will always be present.
+           try:
+               pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
+           except AttributeError:
+               pydantic_extra = None

+           if pydantic_extra is not None:
+               yield from ((k, v) for k, v in pydantic_extra.items())
+
        yield from ((k, getattr(self, k)) for k, v in self.model_computed_fields.items() if v.repr)
```

Minimal example with expected output _after_ proposed changes:
```python
from pydantic.config import ConfigDict
from pydantic.main import BaseModel


class Foo(BaseModel):

    model_config = ConfigDict(extra="allow", extra_repr=False)

    name: str


foo = Foo(name="Bar", Baz="Spam", Eggs="Spam", More="Spam")
print(repr(foo))
# >>> Foo(name='Bar')

print(foo.model_extra)  # No effect.
# >>> {'Baz': 'Spam', 'Eggs': 'Spam', 'More': 'Spam'}

print(foo.model_dump())  # No effect.
# >>> {'name': 'Bar', 'Baz': 'Spam', 'Eggs': 'Spam', 'More': 'Spam'}

```

As you can see, this keeps the `Foo` representation clean/succinct without removing the `model_extra`.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by it176131**
## Change Summary
Added `extra_repr` to the `ConfiDict` (and other necessary spots) + unit tests and docstrings.

## Related issue number
fix #9732 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @PrettyWood

### CODE REVIEW

**Comment by it176131** [comment]
please review

**Review by PrettyWood — COMMENTED** [review]
The code is ok but I'm a bit confused by all those new parameters. The API feels more and more complicated.
I would have prefered just an `extra` parameter where you set if you want extra parameters to be included or not, if you want them to appear in the repr or not, maybe based on some custom logic and not just all or nothing...
I'm not the decision maker here so I'll let the others answer but when I see 40+ params in the config, I feel like we need simplification or more subclasses rather than plenty of true/false params
And people add new params just for one need on issues without any extra demand making the library more complex for everyone

**Comment by it176131** [comment]
> The code is ok but I'm a bit confused by all those new parameters.

May I ask which parameters you're referring to? I've only introduced the `extra_repr` in this PR.

> The API feels more and more complicated. I would have prefered just an `extra` parameter where you set if you want extra parameters to be included or not, if you want them to appear in the repr or not, maybe based on some custom logic and not just all or nothing...

I could refactor [`ExtraValues`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ExtraValues) to do what the proposed `extra_repr` is doing—something like `"allow_no_repr"`? My use case is I have several fields with unknown names coming from an API. Rather than make a bunch of optional fields to catch every case, I allow the model to take extras. After that I have some `computed_fields` look through the `model_extra` and try to convert them into nested models.

> I'm not the decision maker here so I'll let the others answer but when I see 40+ params in the config, I feel like we need simplification or more subclasses rather than plenty of true/false params And people add new params just for one need on issues without any extra demand making the library more complex for everyone

This may be too narrow of a use-case, but thought if I'd run into it others may have as well. I'm open to other alternatives.

**Comment by PrettyWood** [comment]
My comment is not against you but more a general opinion. I didn't say you added a lot of parameters, I just said you added one more and I feel like there are too many or they should at least be simplified or unified in sub structs.
Let's wait for someone from pydantic company.

**Comment by sydney-runkle** [comment]
> I would have prefered just an extra parameter where you set if you want extra parameters to be included or not, if you want them to appear in the repr or not, maybe based on some custom logic and not just all or nothing...

I definitely think this is a good idea - many of the parameters fall under a few select categories, and if we could eventually consolidate settings into things like `extra=ExtraConfig(...)`, that could clean things up a bit, and make settings easier to navigate.

> I'm not the decision maker here so I'll let the others answer but when I see 40+ params in the config, I feel like we need simplification or more subclasses rather than plenty of true/false params

Agreed, see my comment above.

> And people add new params just for one need on issues without any extra demand making the library more complex for everyone

I think the two main things we need to consider when adding a new config param are:

1. What's the demand from the community like?
2. How easy is it for folks to achieve the desired behavior with subclasses / overrides, or other case by case code changes.

In this case, the demand seems relatively low, and it's quite easy to override `__repr_args__` to get the desired behavior. Thus, I don't think this change meets the threshold for a justified new setting.

That being said, I think there is general demand for more customization with `repr` as well as `extra` values, so I'd certainly consider a PR that adds a config setting that addresses multiple of those requests.

@it176131, Thanks for your work and willingness to iterate on this. We'd love to have you as a contributor to other feature requests / changes, if you're interested.

Going to close this as not planned for now.

**Pull request closed without merging**
