### PR TITLE
Provide stacklevel to help users find the warning wrt ConfigDict

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Change Summary

Otherwise the warning points to within pydantic, which makes it really unclear what code is the source of the warning.

## Related issue number

n/a

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
do you really want release notes?

**Review by sydney-runkle — APPROVED** [review]
Looks great, thanks!

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
@hmaarrfk,

Looks great overall. Could you please add a test showcasing why this change is important?

**Comment by hmaarrfk** [comment]
Thanks for the review.

I am unfortunately not going to be able to write a test for this. 

I think that the writing a test for this is just too much churn for me. Sorry.

Take the one liner or leave it.

This helped me in addressing the warning. I'm hoping it can help others in the transition.

**Comment by hmaarrfk** [comment]
I've done tests that inspect warning stack levels before.

If somebody else is interested in doing it, they could get inspired by:
https://github.com/hmaarrfk/wabisabi/blob/main/wabisabi/tests/test_default_parameter_change.py#L76

but unfortunately, I don't have the time or desire to contribute such a test.

**Comment by samuelcolvin** [comment]
Would have taken you less time to write the test than protest. 😉

**Comment by hmaarrfk** [comment]
> Would have taken you less time to write the test than protest. 😉

no. writing wabisabi (and the associated tests) was a multi-day effort. I'm not trying to protest, I am just expressing the amount of technical effort I am willing to do for this change request. And that is to "open github on my browser, and press edit on the upstream projects".

Ensuring stacklevels are correct is an interest of mine, but I understand that it is rather "low value" and alot of churn.
Some other contributor can decide to take off from here and write the test.

In the same light, I feel like pressing "merge" is "lower effort than replying to me" and will avoid you fielding questions from other users. Your choice 🤷🏾 .

Feel free to close if you insist on having a test from me on this particular change proposal.

**Comment by sydney-runkle** [comment]
I'm going to close this for now - using a basic example locally, I wasn't able to realize the benefit of this stacklevel change. If anyone wants to reopen this and add a test at any point proving the benefit, feel free!

Thanks for getting the work started, @hmaarrfk.

**Comment by hmaarrfk** [comment]
Thanks for taking the time to try it out locally!

**Pull request closed without merging**
