### PR TITLE
Parse Decimal in python to avoid precision loss 

### LINKED ISSUE #6295: Decimal Deserialization Doesn't Maintain Accuracy
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

While using FastAPI 0.100.0b1 and Pydantic 2.0b3 I've noticed that decimals deserialized from JSON no longer maintain the accuracy as stated in the [documentation](https://docs.pydantic.dev/dev-v2/usage/types/number_types/#validation-of-numeric-types).

>  Pydantic attempts to convert the value to a string, then passes the string to Decimal(v).

It's clear from simple testing that Pydantic v2 no longer does this, and the behavior matches what would happen if you created a decimal from a float, like so:

```python
decimal.Decimal(48.717983)
```

where the documentation (and v1 behavior) states that the following should happen:

```python
decimal.Decimal("48.717983")
```

This behavior results in decimal fields that do not accurately match the intended value.

### Example Code

```Python
#!/usr/bin/env python

import decimal
import pydantic

data = '{"number":48.717983}'

class Test(pydantic.BaseModel):
    number: decimal.Decimal

parsed = Test.model_validate_json(data)  # use parse_raw for v1
expected = decimal.Decimal("48.717983")
assert parsed.number == expected
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b3
        pydantic-core version: 0.42.0 release build profile
                 install path: /Users/stephen/code/pydantic/pydantic
               python version: 3.11.4 (main, Jun 13 2023, 16:13:25) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
```


Selected Assignee: @dmontagu

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #6295

Selected Reviewer: @lig

### CODE REVIEW

**Comment by adriangb** [comment]
please review

**Comment by adriangb** [comment]
Quick benchmark vs main:

image
image


So a bit of a slowdown, but not super significant.

**Review by lig — APPROVED** [review]
👍🏻

**Comment by san595** [comment]
632

**Comment by adriangb** [comment]
> 632

?

**Comment by san595** [comment]
https://github.com/pydantic/pydantic/pull/6321#issuecomment-1620865639

**Comment by san595** [comment]
https://github.com/pydantic/pydantic/pull/6321#issuecomment-1620865639

**Pull request merged**
