### PR TITLE
:memo: Add ISBN Documentation to navigation

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

Adding documentation for a new extra type added in https://github.com/pydantic/pydantic-extra-types/pull/116

## Related issue number

https://github.com/pydantic/pydantic-extra-types/issues/115

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Review by sydney-runkle — APPROVED** [review]
Looks great, thanks!

**Comment by sydney-runkle** [comment]
We'll have to wait on a new version of `pydantic_extra_types` for this, but otherwise looks great!

**Comment by sydney-runkle** [comment]
@yezz123,

Could you please pull in the changes from `main`? I think that'll fix the docs build (I updated the `pydantic-extra-types` version on `main`)

**Comment by yezz123** [comment]
> @yezz123,
> 
> Could you please pull in the changes from `main`? I think that'll fix the docs build (I updated the `pydantic-extra-types` version on `main`)

Done, its updated

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Really they'll have to be in the `pydantic-extra-types` repo

**Comment by sydney-runkle** [comment]
@yezz123,

Could you please bump the `pydantic-extra-types` version here to `2.4.1`? I'm working on getting that release out now 👍

**Review by sydney-runkle — APPROVED** [review]
Nice, thanks for the help!

**Comment by yezz123** [comment]
> Nice, thanks for the help!

@sydney-runkle i was OOO that's why!

Thank you for making the changes 🙏🏻

**Comment by sydney-runkle** [comment]
@yezz123 no worries at all. Sure thing! The release took a while anyways, so I took a break as well, haha.

**Pull request merged**
