### PR TITLE
🔧 Add Currency and Language code documentation

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

I added the documentation for 2 new types, Currency and language

## Checklist

* [X] The pull request title is a good summary of the changes - it will be used in the changelog
* [X] Unit tests for the changes exist
* [X] Tests pass on CI
* [X] Documentation reflects the changes where applicable
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @adriangb

### CODE REVIEW

**Comment by yezz123** [comment]
please review

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Looks good, but we'll also want to update the `pdm.lock` and requirements file to use the new `pydantic-extra-types` version once we release that 👍

**Comment by yezz123** [comment]
@sydney-runkle i updated the Pull request with the changes regarding pedantic-extra and seems like Github is down 😞 

Overall the PR is ready to merge

https://github.com/pydantic/pydantic/compare/main...yezz123:pydantic:docs/new?expand=1

Screenshot 2024-03-01 at 15 50 45

**Comment by sydney-runkle** [comment]
@yezz123,

Looks like the docs build is having a problem - could you test it against 2.6 locally and figure out what might be the issue there?

**Comment by yezz123** [comment]
> @yezz123,
> 
> Looks like the docs build is having a problem - could you test it against 2.6 locally and figure out what might be the issue there?

because 2.6.0 its not yet released check here

https://github.com/pydantic/pydantic-extra-types/actions/runs/8112776783/job/22174747195

https://pypi.org/project/pydantic-extra-types/2.6.0/

**Pull request merged**
