### PR TITLE
Update mkdocs.yml

### PR DESCRIPTION
**Pull request by Kludex**
https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button

### CODE REVIEW

**Review by hramezani — APPROVED** [review]
Thanks @Kludex :+1: 

I think we can backport this to [1.10.X](https://github.com/pydantic/pydantic/tree/1.10.X-fixes)

**Comment by Kludex** [comment]
I was too tired to write a meaningful description, but I guess you got it. 😎👍

**Comment by hramezani** [comment]
Thank you so much @Kludex.

Would you like to create backport PR as well? Otherwise, I can take care!

**Comment by samuelcolvin** [comment]
Thanks both, this is great.

**Comment by Kludex** [comment]
> Thank you so much @Kludex.
> 
> Would you like to create backport PR as well? Otherwise, I can take care!

Go ahead. 👀🏃💨🙏

**Pull request merged**
