### PR TITLE
Added more detailed documentation plus several code examples for ImportString #537

### PR DESCRIPTION
**Pull request by ybressler**
Added enhanced documentation for the specifics of `ImportString`.

### Some important details:
* Created a new subsection in `types` docs for "exotic types"
  * The term "exotic type" is pretty fun, and I have seen it used loosely in various documentation guides. But I don't have a "text book definition" for it. What I mean to say is, perhaps `"exotic types"` is appropriate section title, perhaps not.
* Added some examples of expected "good behavior" for `ImportString`
* Added some examples of expected "bad behavior"  for `ImportString`
* Added an example of _**unexpected "bad behavior"**_ as well 😢
  * Maybe there's a solution we can employ (or a workaround) in the code example. If not, I think it's best to document what doesn't work, save people some headaches.

**Side note:** This is my first PR for pydantic! Woot woot!

### CODE REVIEW

**Comment by ybressler** [comment]
Oh dear, it looks like I didn't check out the branch correctly? (Why is it showing ~70 commits from other authors?) I'm sorry, I don't know how to get rid of that....

**Comment by ybressler** [comment]
Ok, I definitely didn't do something right. The extra 70 commits are going to make reviewing my code impossible. It's late at night. I'm gonna step away from this and review tomorrow. If you have a ready to go solution, please share. Otherwise, I'll figure it out later myself, when I am more well rested.

**Comment by samuelcolvin** [comment]
Most likely you didn't base your changes of the target branch.

Probably easier to create a new pr and either cherry pick your commits or copy and paste them.

You need to target the `main` branch.

**Comment by ybressler** [comment]
> Most likely you didn't base your changes of the target branch.
> 
> Probably easier to create a new pr and either cherry pick your commits or copy and paste them.
> 
> You need to target the `main` branch.

AH. I didn't target `main`, instead, targeted a documentation branch. Fixed.

**Pull request closed without merging**
