### PR TITLE
📝  Add Pendulum Documentation to navigation

### PR DESCRIPTION
**Pull request by yezz123**
## Change Summary

Until we release a new version 2.5.0

## Related issue number

https://github.com/pydantic/pydantic-extra-types/pull/127

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @dmontagu

### CODE REVIEW

**Comment by sydney-runkle** [comment]
@yezz123,

Thanks a bunch. Could you please update the version of `pydantic-extra-types` used here so that the docs build will succeed? I've just released 2.5.0 :).

**Comment by yezz123** [comment]
@sydney-runkle the PR is ready

**Comment by yezz123** [comment]
please review

**Review by sydney-runkle — APPROVED** [review]
Thanks! Looks great

**Comment by sydney-runkle** [comment]
https://docs.pydantic.dev/dev/api/pydantic_extra_types_pendulum_dt/

Looks great, thanks!

**Pull request merged**
