### PR TITLE
Add test for deprecation warning in V1 isinstance check

### LINKED ISSUE #10497: Internal Pydantic code issuing warnings
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm running my tests with `pytest -W error` and found a place where Pydantic is issuing deprecation warnings against its own code. As a user, I can't really fix this, as I'm not calling any deprecated functions myself, and I'd rather not have to suppress warnings for code I don't own. Specifically, if I do `isinstance(v2_instance, v1.BaseModel)`, I get

```text
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    isinstance(foo, pydantic.v1.BaseModel)
  File "pydantic/v1/main.py", line 304, in __instancecheck__
    return hasattr(instance, '__fields__') and super().__instancecheck__(instance)
  File "pydantic/main.py", line 1090, in __fields__
    warnings.warn(
pydantic.warnings.PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
```

Would it be ok to fix this? ~One option would be to wrap this `hasattr` call in a `catch_warnings` block and ignore this warning.~ _Edit: not an option; see below._ Alternatively, perhaps we could check a different attribute? Or check a V2 attribute first then fall back to a V1 one?

### Example Code

```Python
import pydantic, pydantic.v1, warnings

class Foo(pydantic.BaseModel):
  bar: str

foo = Foo(bar="txt")

warnings.simplefilter("error")
isinstance(foo, pydantic.v1.BaseModel)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/apurcell14/code/hera/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Mar  4 2024, 14:30:04)  [GCC 11.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 mypy-1.9.0
                       commit: unknown
```

### PR DESCRIPTION
**Pull request by alicederyn**
## Change Summary

The v1 ModelMetaclass isinstance check first looks for a `__fields__` attribute before delegating to the costly ABC superclass's implementation. Unfortunately, this attribute raises a DeprecationWarning if a v2 model is passed into isinstance.

#10645 changes the logic to check the `__post_root_validators__` attribute, which is not present on v2 models. However, it cannot include a test, as the test needs access to V2 models. This PR adds the test that will start passing once the change is merged into the main branch, marked as xfail for now. (See https://github.com/pydantic/pydantic/pull/10642#issuecomment-2419287314)

## Related issue number

Fixes #10497 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [X] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by sydney-runkle** [comment]
LGTM, but we'll need to merge this into `1.10.X-fixes`, so you'll probably want to fork from there as well. Going to close for now, please reopen against this branch :).

**Comment by alicederyn** [comment]
I don't think we can test this there?

**Comment by sydney-runkle** [comment]
Right, we bundle V1 into V2, which we'll do in our next release.

**Comment by alicederyn** [comment]
But the tests I have written won't work on the V1 branch.

**Comment by sydney-runkle** [comment]
That's fine, we can do this as 2 separate PRs then - the tests against `main` and the patch against the v1 patches.

**Comment by sydney-runkle** [comment]
So, we'll want to remove the code change to `v1/...` here, but you can leave the test. Let's mark it as xfail for now (then merge), and we'll remove the mark once we bump the V1 version inside of V2.

**Review by sydney-runkle — APPROVED** [review]
Nice work, thanks!

**Pull request merged**
