### PR TITLE
adds test case for unexpected discriminated union behavior

### PR DESCRIPTION
**Pull request by kf-novi**
## Change Summary
Adds failing test case for expected behavior in discriminated union `model_dump`

## Related issue number

#9235 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by sydney-runkle** [comment]
Thanks for adding the test case! Please remove all of the other changes made in this PR (reformatting), etc

**Comment by kf-novi** [comment]
Ah can I just do make format for that?

**Comment by sydney-runkle** [comment]
@kf-novi I believe so, or just revert the commit + add back the test if that doesn't work

**Comment by kfreezen** [comment]
reverted and added test back. Seems that ruff format doesn't remove trailing commas that my auto-formatter added.

**Comment by kf-novi** [comment]
Sorry about the dual account thing here, opened with this one and keep forgetting which one I'm using. Anyway, had to revert since my auto-formatter added a bunch of commas that ruff format doesn't remove. So, should be good now.

**Comment by sydney-runkle** [comment]
@kf-novi,

Maybe add an `xfail` with a link to your issue, then we can merge this?

**Comment by kfreezen** [comment]
I will do that tomorrow!

**Comment by sydney-runkle** [comment]
@kf-novi @kfreezen :),

Wonderful, thanks for your help here!

**Review by sydney-runkle — APPROVED** [review]
Nice, including this in the patch and hoping we can get a fix for this in 2.8

**Pull request merged**
