### PR TITLE
Added abstract SecretField class for secret fields

### PR DESCRIPTION
**Pull request by expobrain**
## Change Summary

This PR adds a `SecretField` abstract class to be used to derive `SecretStr` and `SecretBytes` and any other future secret fields so that to check if a Pydantic field is a secret one it's not possible by just using `issubclass()` instead of by duck typing with `hasattr(model, 'get_secret_value')`.

## Related issue number

Fixes #3409.

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by expobrain** [comment]
please review

**Comment by expobrain** [comment]
Please review, I'm not sure what's the best way to test this line https://smokeshow.helpmanual.io/2j4q0c1o1a121f3l3l5m/d_2705a9c05af28909_types_py.html#t825 so that code coverage reaches the 100% mark again.

**Review by samuelcolvin — APPROVED** [review]
LGTM. thanks for contributing.

I'll merge once v1.9.1 is done, this can go in 1.10.

**Comment by samuelcolvin** [comment]
great, thanks so much.

**Pull request merged**
