### PR TITLE
Remove trailing "```" from docs

### PR DESCRIPTION
**Pull request by Kludex**
I'm not sure how this interferes with the migration to V2... :eyes:

### CODE REVIEW

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
Thanks @Kludex

**Comment by Kludex** [comment]
btw, the "This script is complete" and the "outputs" are in the same line, I'm not sure if this is intended...
 
image

**Comment by hramezani** [comment]
I think yes, and the `Outputs` indicated the next block is the output of the execution.

**Comment by Kludex** [comment]
But if you look at other pages, the "Outputs:" would have their own new line :eyes: 

Ref.: https://pydantic-docs.helpmanual.io/usage/validators/

Anyway... :wave: :runner: :dash:

**Comment by Kludex** [comment]
> But I can't see Outputs on the page that you've referenced. I can only see (This script is complete, it should run "as is") (without Outputs:)

Based on this, I don't think I expressed myself very well.

> FYI, Outputs is used for presenting the JSON output of scripts. and will be appended to the script in

I got that, what I'm saying is that a new line is missing before `Outputs:`, because it looks like (based on the rest of the docs) that it's not intended to be in the same line as the "This script is complete..."

**Comment by samuelcolvin** [comment]
Ye I think you're right, "Outputs:" should be a shown on a new line.

**Comment by hramezani** [comment]
Thanks @Kludex for explaining. Yes, you are right.

@samuelcolvin I can take care of it.

**Pull request merged**
