### PR TITLE
Use constraints files for requirements

### PR DESCRIPTION
**Pull request by adriangb**
Use the `all.txt` as a constraints file for the other lockfiles. This ensures that there is no incompatibilities between the different environments.

Selected Reviewer: @dmontagu

### CODE REVIEW

**Comment by samuelcolvin** [comment]
conflicts, please update.

**Comment by adriangb** [comment]
please review

**Comment by dmontagu** [comment]
And to be clear, as far as I'm concerned, this is fine if it's working (and CI seems to indicate it is).

I guess the only thing I would request is adding a brief comment (one line is enough) in the Makefile and/or shell scripts that explains the difference between `refresh_lockfiles` and `rebuild_lockfiles`. I see this is described in the README.md but I'm less likely to find it there when trying to remember what does what.

**Comment by adriangb** [comment]
I added some comments explaining what the commands do and the check for `pip-tools` being installed that you suggested in Slack

**Comment by samuelcolvin** [comment]
This is great, thank you.

**Pull request merged**
