### PR TITLE
Use correct types namespace when building namedtuple core schemas

### PR DESCRIPTION
**Pull request by Viicos**
## Change Summary

Fixes https://github.com/pydantic/pydantic/issues/10336

Regression introduced in https://github.com/pydantic/pydantic/pull/10063

See diff [without whitespaces](https://github.com/pydantic/pydantic/pull/10337/files?diff=split&w=1)

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Review by sydney-runkle — APPROVED** [review]
Great find @Viicos. Do we need to make any changed to typed dicts (I see we also changed that schema gen func in the original PR)

Feel free to remove that benchmark for now (let's comment it out), it's too flaky to be valuable at this point.

**Comment by Viicos** [comment]
> Feel free to remove that benchmark for now (let's comment it out), it's too flaky to be valuable at this point.

I have a pending PR that I'll finish this afternoon to tackle this

**Comment by sydney-runkle** [comment]
Sounds good. Also, could you please add a test before we merge?

**Review by sydney-runkle — APPROVED** [review]
Great work!

**Pull request merged**
