### PR TITLE
Added bits conversion to the ByteSize class feature #8415

### PR DESCRIPTION
**Pull request by luca-matei**
## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by luca-matei** [comment]
Hello, please review

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Hi @luca-matei,

Thanks for getting a start on this! Looks good overall.

Could you please add some tests (maybe a parametrized test, or extend a current parametrized test) to test these cases? Thanks! 🚀

**Comment by luca-matei** [comment]
> Hi @luca-matei,
> 
> Thanks for getting a start on this! Looks good overall.
> 
> Could you please add some tests (maybe a parametrized test, or extend a current parametrized test) to test these cases? Thanks! 🚀

Sure thing! Here's the updated PR

**Review by sydney-runkle — APPROVED** [review]
Looks great, thanks for adding tests!

**Comment by luca-matei** [comment]
Happy to help!

**Pull request merged**
