### PR TITLE
Support __get_validators__

### PR DESCRIPTION
**Pull request by hramezani**
Closes https://github.com/pydantic/pydantic/issues/6899

### CODE REVIEW

**Review by samuelcolvin — COMMENTED** [review]
we should add a deprecation warning, otherwise LGTM.

**Review by adriangb — COMMENTED** [review]
Do we care how this interacts with `Annotated`, including with other classes that implement `__get_pydantic_core_schema__`? Might be worth testing

**Comment by hramezani** [comment]
> Do we care how this interacts with `Annotated`, including with other classes that implement `__get_pydantic_core_schema__`? Might be worth testing

@adriangb, I think we already have a test for this. Is that enough?

https://github.com/pydantic/pydantic/blob/d110b47803eb484bbc85cf9a2105e24a5852c2e2/tests/test_deprecated.py#L498-L523

**Comment by adriangb** [comment]
But that doesn't use this new / old `__get_valdiators__` right?

**Review by adriangb — APPROVED** [review]

**Pull request merged**
