### PR TITLE
Fix duplicate test name

### PR DESCRIPTION
**Pull request by mot3**
There was a duplicate name in file

    tests/test_aliases.py

test_alias_generator function
I had #9384 discussion before

### CODE REVIEW

**Comment by Viicos** [comment]
Nice, but I've pushed a PR already: https://github.com/pydantic/pydantic/pull/9387 :smile:

**Comment by mot3** [comment]
> Nice, but I've pushed a PR already: https://github.com/pydantic/pydantic/pull/9387 :smile: 

I closed it but your pull request has one failed

**Comment by Viicos** [comment]
> I closed it but your pull request has one failed

It is just a matter of maintainers adding the appropriate label

**Comment by mot3** [comment]
> > I closed it but your pull request has one failed
> 
> It is just a matter of maintainers adding the appropriate label

Why did mine have 3 failed?

**Pull request closed without merging**
