### PR TITLE
Added validation_error_cause to config.

### LINKED ISSUE #6498: raise Err() from e and e.add_note() lose information in validation errors
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Edit: `2` is actually a regression from v1, in 1.10.11 the outputted error was `Must be greater than 5 (type=assertion_error; __notes__=['ERR NOTE!'])`.

Errors in V2 are on another level to V1, but error manipulation still loses information in the final `ValidationError` outputted by pydantic when:

1. Catching an error, raising an outer error using the `from e` syntax 
    - with pd: the inner error is lost
2. adding notes to errors using `e.add_note()` 
    - with pd: the note is lost

In both cases information is lost, which can be very useful when complex multi-func validation is going on to add context to inner errors at the top level. 

I don't think either are a security concern being enabled by default in pydantic, both are opt in with `from e` and `add_note` respectively.

```Python
from pydantic import BaseModel, field_validator

class Foo(BaseModel):
    foo: int
    bar: int

    @field_validator("foo")
    def val_foo(cls, v: int) -> int:
        try:
            assert v > 5, "Must be greater than 5"
        except AssertionError as e:
            raise ValueError("OUTER EXC!") from e

        return v

    @field_validator("bar")
    def val_bar(cls, v: int) -> int:
        try:
            assert v > 5, "Must be greater than 5"
        except AssertionError as e:
            e.add_note("ERR NOTE!")
            raise e

        return v
        

Foo(foo=4, bar=4)
```

Results in
```
Traceback (most recent call last):
  File "mypy_playground.py", line 28, in <module>
    Foo(foo=4, bar=4)
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Foo
foo
  Value error, OUTER EXC! [type=value_error, input_value=4, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/value_error
bar
  Assertion failed, Must be greater than 5 [type=assertion_error, input_value=4, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/assertion_error
```

Native errors when outside pydantic:
```
Traceback (most recent call last):
  File "mypy_playground.py", line 7, in <module>
    raise e
  File "mypy_playground.py", line 4, in <module>
    assert v > 5, "Must be greater than 5"
           ^^^^^
AssertionError: Must be greater than 5
ERR NOTE!
```

```
Traceback (most recent call last):
  File "mypy_playground.py", line 4, in <module>
    assert v > 5, "Must be greater than 5"
           ^^^^^
AssertionError: Must be greater than 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mypy_playground.py", line 6, in <module>
    raise ValueError("OUTER EXC!") from e
ValueError: OUTER EXC!
```

```
             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

### PR DESCRIPTION
**Pull request by zakstucke**
## Change Summary
Hooks up `validation_error_cause: bool` config value added to pydantic core.

## Related issue number
Fix #6498 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by zakstucke** [comment]
please review

**Comment by hramezani** [comment]
Thanks @zakstucke for this patch 🙏 

It would be great to have at least one test for this config flag.

Please update

**Comment by zakstucke** [comment]
@hramezani its got quite a few different pathways tested fully in pydantic core. Do you want me to add exception group as a test dep in pydantic as well and test all the different pathways, or something simpler?

Pathways: 
- Disabled, nothing
- <3.11, enabled no backport -> ImportError
- <3.11 with backport -> works using UserWarning
- >=3.11 with/without backport -> works using notes

**Comment by zakstucke** [comment]
@hramezani ok sounds good, just added test for 3.11 modern pathway, disabled and enabled.

**Comment by zakstucke** [comment]
@hramezani

**Comment by hramezani** [comment]
Thanks @zakstucke for refreshing the PR, we will include this in the next release

**Review by sydney-runkle — APPROVED** [review]
Looks great! Thanks @zakstucke for the contribution 😄

**Comment by sydney-runkle** [comment]
@zakstucke, do you want to change the description of this PR to have Fix #6498? instead of just the issue reference?

**Comment by zakstucke** [comment]
@sydney-runkle done! (If I understood you correctly)

**Pull request merged**
