### PR TITLE
[cherry-pick] Fix mypy plugin for 1.4.0 (#5927)

### PR DESCRIPTION
**Pull request by cdce8p**
## Change Summary
Cherry-pick of #5927
Adapted for `1.10.X`.

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @PrettyWood

### CODE REVIEW

**Comment by cdce8p** [comment]
please review

**Review by hramezani — APPROVED** [review]

**Comment by cdce8p** [comment]
#5927 was just merged.

After this PR is merged as well, it would be awesome if `1.10.9` could be released. That would make testing mypy dev versions a bit easier.

**Comment by hramezani** [comment]
@samuelcolvin Do we plan to prepare a new release for `1.10.x` to include this change?

If so, I can handle it

**Comment by cdce8p** [comment]
Any update on a `1.10.9` release? The next mypy release (which breaks the `1.10.8` plugin) is currently scheduled for early July (about a month). It would be awesome to have the fix released sooner rather than later to give people enough time to update and make the transition as painless as possible.

**Comment by samuelcolvin** [comment]
good idea, will do.

**Pull request merged**
