### PR TITLE
🧱 Add Giscus comment system to the documentation

### PR DESCRIPTION
**Pull request by Kludex**
This PR adds a comments section at the end of each documentation page.

Screenshot 2023-06-12 at 18 00 59

Ref.:
- Comment system: https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/
- Meta plugin: https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins

### CODE REVIEW

**Comment by Kludex** [comment]
> ## Deploying with  [Cloudflare Pages](https://pages.dev)  Cloudflare Pages
> **Latest commit:**	`0e5c03a`
> **Status:**	🚫  Build failed.
> [View logs](https://dash.cloudflare.com/?to=/:account/pages/view/pydantic-docs/6bc59fba-8762-4ec9-94cd-d55fce042a67)

I can't see how they failed. Can you check this, please @samuelcolvin ?

**Comment by Kludex** [comment]
It may be failing because of the version of mkdocs-material-insiders... 🤔

**Comment by samuelcolvin** [comment]
Build error:

```
16:57:39.635 | + python3 -m pdm run python -c 'import docs.plugins.main'
-- | --
16:57:41.952 | + python3 -m pdm run mkdocs build --config-file mkdocs.insiders.yml
16:57:44.609 | ERROR    -  Config value 'plugins': The "meta" plugin is not installed
16:57:44.610 | Aborted with 1 Configuration Errors!
16:57:44.748 | Failed: Error while executing user command. Exited with error code: 1
16:57:44.758 | Failed: build command exited with code: 1
16:57:45.872 | Failed: error occurred while running build command
```

**Comment by samuelcolvin** [comment]
please update. I'm going to sort cloudflare so you can view the build log once I've gone through other PRs.

**Comment by Kludex** [comment]
Closing as stale. We can come back to this later on. There are far more important things on the documentation to work right now.

**Pull request closed without merging**
