### PR TITLE
Create release.yml

### PR DESCRIPTION
**Pull request by tim-habitat**
## Change Summary

This PR adds a `.github/release.yml` file to enable auto-generation of release notes using the existing labels for pull requests. The release notes will be organized into categories based on the labels, making it easier for users to understand the changes in each release. I understand that tools like Release Drafter are popular choices for generating release notes, but they require additional setup and CI (e.g., GitHub Actions). This proposed solution will only be applied when clicking the auto-generate button when writing release notes on GitHub. As a suggestion, it might be a good idea to include "Add label to the PR checklist" in the PR template. Else, i believe we can also add auto-labelling if using Release Drafter.

This is a proposal and I am very open to modifying the name, adding, or removing sections based on the project's requirements and preferences. Let me know your preference.

Thanks for a great library!

## Related issue number

This PR does not directly address any open issues. However, it will improve the release process by auto-generating organized release notes.

## Checklist

* [x] Unit tests for the changes exist (not applicable for this change)
* [x] Tests pass on CI and coverage remains at 100% (not applicable for this change)
* [x] Documentation reflects the changes where applicable (not applicable for this change)
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

## Example

Below is a dummy example of what it could look like (if the pr had the proper labels):

What's Changed
----
### ✨ Features
- Feature 1 (#1)
- Feature 2 (#3)
- Feature 3 (#5)

### 🐞 Bug fixes
- Fixed bug 1 (#2)
- Fixed bug 2 (#6)

### 👒 Dependencies
- Updated dependency 1 (#4)
- Updated dependency 2 (#7)

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I don't really agree with this. Once we're past alpha releases, we want to use change files, see https://github.com/pydantic/pydantic/tree/main/changes

We could change the format to include features, bugfix etc.

We also want to write this to History.md, and use that content in the release.

WDYT?

**Comment by samuelcolvin** [comment]
No I'm intending to
* Run the script in changea
* Check history.md is right
* Commit
* Copy the new content from history.md in to release notes

Remember, we need history.md:
* The docs site
* the readme uploaded to pypi

**Comment by tim-habitat** [comment]
Ah ok sorry i didn't know this was the process. 

I'll take a look and see if we can replicate the categorising when running the scripts so it is formatted when pushing to `history.md`. Does that seem to make more sense then ?
Or would you like to keep `history.md` in another specific format ?

**Comment by samuelcolvin** [comment]
happy to consider categorisation in `history.md`, it would need to work via a new change file name format, e.g. `1234.feature.samuelcolvin.md`.

To do this we'd need to:
* update the readme
* update `make_history.py`
* update hooky to check for those formats and error if they're wrong

Honestly right now that's pretty far down my list of priorities while trying to get V2 released.

**Comment by tim-habitat** [comment]
> Honestly right now that's pretty far down my list of priorities while trying to get V2 released.

I understand - i'll close this PR then and perhaps try to open a new one with those changes in mind once v2 has been released. 
Good luck with the release, excited about it!

**Pull request closed without merging**
