### PR TITLE
Add a linting integrations section to docs

### PR DESCRIPTION
**Pull request by Viicos**
Might help having the plugin get some visibility. In the future, I might implement these rules in Ruff itself, so it would also fit under the `Linting` section as well

Selected Reviewer: @adriangb

### CODE REVIEW

**Comment by Viicos** [comment]
Please review

**Review by sydney-runkle — APPROVED** [review]
Sure thing! Thanks!

**Comment by sydney-runkle** [comment]
Feel free to open a PR on https://github.com/Kludex/awesome-pydantic/pulls as well, if you want

**Comment by Viicos** [comment]
Oh didn't know about this one, nice!

**Pull request merged**
