### PR TITLE
Fix the behavior change in `.json()` documentation

### PR DESCRIPTION
**Pull request by hramezani**
## Related issue number
fix https://github.com/pydantic/pydantic/issues/3780

skip change file check
## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/pydantic/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Comment by samuelcolvin** [comment]
LGTM, could you also add a `**Breaking Change, see #3780**:` to `HISTORY.md` for the original change that caused this?

If that's not possible or doesn't make sense, feel free to merge this, otherwise please update.

**Comment by hramezani** [comment]
> LGTM, could you also add a `**Breaking Change, see #3780**:` to `HISTORY.md` for the original change that caused this?
> 
> If that's not possible or doesn't make sense, feel free to merge this, otherwise please update.

I think it makes sense. I added it.
please review

**Comment by samuelcolvin** [comment]
LGTM, thanks so much.

**Pull request merged**
