### PR TITLE
Add tests for mypy inspection of metaclass arguments

### LINKED ISSUE #5858: pydantic.mypy doesn't respect metaclass arguments.
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

It seems like when using metaclass arguments for the base model (e.g. `class Foo(BaseModel, arg1=..., arg2=...)`) that pydantic.mypy ignores them. I found this out when setting `allow_population_by_field_name` this way. Note that I am running with the `init_typed=True` setting.

The options do appear to work at runtime, just not not during type checking.

As a workaround the `Config` nested class is still respected by pydantic.mypy, so this gets me out of hot water.

Apologies if this is a duplicate, after searching I couldn't find any matches. Feel free to close if so!

### Example Code

```Python
from pydantic import BaseModel, Field


class MypyCorrectError(BaseModel):
    i: int = Field(2, alias="j")

    class Config:
        allow_population_by_field_name = True


# error: Argument "i" to "MypyCorrectError" has incompatible type "None"; expected "int"  [arg-type]
MypyCorrectError(i=None)


class MypyWrongError(BaseModel, allow_population_by_field_name=True):
    i: int = Field(alias="j")


# error: Missing named argument "j" for "MypyWrongError"  [call-arg]
MypyWrongError(i=None)


class MypyFalsePositive(BaseModel, allow_population_by_field_name=True):
    i: int = Field(2, alias="j")


# No error listed for using None instead of int.
MypyFalsePositive(i=None)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
pydantic compiled: True
install path: /Users/.../lib/python3.10/site-packages/pydantic
python version: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.3.1-arm64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by cpratt34**
Following up on #5858, it appears that v2 of pydantic seems to respect the metaclass arguments when evaluating types. Adding additional unit tests to ensure this behavior remains stable.

I will follow up with a PR to make a similar test in v1, along with any changes needed.

## Change Summary

Add unit tests that assert the metaclass argument behavior function properly in v2.

## Related issue number

Fix #5858

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @lig

### CODE REVIEW

**Comment by cpratt34** [comment]
Was able to see the CI tests run to completion on my fork. please review

**Review by lig — APPROVED** [review]
LGTM

More tests is better:)

**Comment by lig** [comment]
@cpratt34 Thank you for the contribution!

**Comment by lig** [comment]
CI keeps failing on this branch. I believe it's because your branch uses an old configuration. Could you please rebase your branch on the latest `main` of the `pydantic` main repo?

I've tried doing that here https://github.com/pydantic/pydantic/pull/6029 and it seems to be working.

**Comment by cpratt34** [comment]
Rebased! Lets see if that helps 😄

**Comment by lig** [comment]
@cpratt34 docs builds aren't working at the moment there will be a fix in `main` for that today. Let's wait for it and than rebase.

**Comment by cpratt34** [comment]
Okay, rebased again! :)

**Review by dmontagu — APPROVED** [review]

**Comment by cpratt34** [comment]
Thanks @dmontagu and @lig ! 
I'll get started on the 1.X port of this!

**Pull request merged**
