### PR TITLE
Get frozen fields working

### PR DESCRIPTION
**Pull request by dmontagu**
I don't love this approach, but it works.

I'd be happy to rework this with another approach, the main benefit to this approach is that it fully re-uses the existing annotation-unwrapping logic.

Selected Reviewer: @adriangb

### CODE REVIEW

**Comment by dmontagu** [comment]
please review

**Comment by adriangb** [comment]
@samuelcolvin David and I discussed a bit offline. We both feel that this implementation works, but isn't ideal because the existing codebase isn't really designed to support this. We're not sure what the right path forward is but I am assigning this to you so that you can decide if you want to merge this as-is or think about a large scale rework in this area.

**Comment by samuelcolvin** [comment]
let's think about it rather than doing anything in a hurry.

**Comment by dmontagu** [comment]
Closing in favor of #5354

**Pull request closed without merging**
