### PR TITLE
Add benchmarks for categories: serialization, validation and schema generation

### LINKED ISSUE #9711: Expand breadth of benchmarks
We have a robust benchmark test suite in `pydantic-core`, but are lacking similar coverage in `pydantic`.

Specifically, I'm interested in expanding this test suite in relation to our core schema build times, as we're looking to improve performance there in the short term. Secondarily, I'm interested in better benchmarking for our json schema generation. Benchmarks for validation and serialization are great, but we've already got pretty good coverage in `pydantic-core` for those, so I'm less concerned about such benchmarks.

This is a great first issue - you can help write tests that test a variety of use cases for `pydantic`, without having to delve into the internals of `pydantic` code to fix bugs or add new features.

Here are some cases for which I think we should expand our suite of benchmarks (assume these are for core schema generation, but you can write related tests for any of the above mentioned categories). As in, you could read the first bullet as "we need to write some tests showcasing how long schema building takes for models with custom validators".

- [x] custom validators (field and model, also before, wrap, after, and plain)
- [x] tagged and untagged unions
- [x] stdlib types
- [x] second class Pydantic types like `SecretStr` and `PositiveInt`
- [x] custom serializers (field and model, also before, wrap, after, and plain)
- [x] recursive model definitions -- need much more robust testing when defs / refs are involved
- [ ] third party, custom types

I wouldn't say these are necessary to close this issue, but one thing for more involved contributors to look at would be benchmarking specific parts of our core schema generation process in `pydantic`, such as:

- [ ] annotation application
- [ ] discriminator application
- [ ] schema cleaning (including defs / refs simplification)
- [ ] schema walking
- [ ] field acquisition / setup in `ModelMetaClass.__new__`

### PR DESCRIPTION
**Pull request by AdolfoVillalobos**
## Change Summary

I created three tests to benchmark Pydantic's performance in basic categories:

- Schema generation
- Serialization
- Validation.

The tests handle varying levels of complexity ranging from simple tests to nested scenarios, inspired by the pydantic-core test suite. 

## Related issue number

Contributes to #9711 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by AdolfoVillalobos** [comment]
I'm lost as to why the tests are failing. I can't see how my code is impacting them. I would really appreciate some advice ;)  Thanks!

**Comment by Viicos** [comment]
Thanks for taking a stab at this. Regarding the benchmarks related to core schema generation, I'll probably expand these to meet my needs (related to https://github.com/pydantic/pydantic/pull/10223).

**Comment by sydney-runkle** [comment]
Hmm, test failure does seem odd.

@AdolfoVillalobos, amazing work here - thanks for helping us to expand our benchmarks!

**Comment by sydney-runkle** [comment]
So odd, I can't repo that test failure locally, even when pulling your changes

**Review by sydney-runkle — APPROVED** [review]
I'll investigate this test failure on a separate branch, but have pushed a patch fix for now.

**Comment by AdolfoVillalobos** [comment]
> Thanks for taking a stab at this. Regarding the benchmarks related to core schema generation, I'll probably expand these to meet my needs (related to #10223). I'll make sure to add you as a co-author.

I'm glad this PR was helpful ;) Thanks!

**Comment by AdolfoVillalobos** [comment]
> I'll investigate this test failure on a separate branch, but have pushed a patch fix for now.

Yess, it was a bit odd. I still don't quite get what was broken.

In any case, thanks for the help and support ;). 

I love this project; It has helped me many times, so I am happy and proud to make my first contribution. Hopefully, I will continue to contribute in the future ;)

**Pull request merged**
