### PR TITLE
Use union_schema with Type[Union[...]]

### LINKED ISSUE #6815: Field of Type[Union[...]] fails in V2
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic V2 no longer supports annotating a field using `Type` before `Union`. A model with the following field:
```python
Type[Union[str, bytes]]
```

Gives the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 174, in __new__
    complete_model_class(
  File "/home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 449, in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(simplified_core_schema, core_config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
  SchemaError: Error building "model-fields" validator:
  SchemaError: Field "s":
  SchemaError: Error building "is-subclass" validator:
  TypeError: '_UnionGenericAlias' object cannot be converted to 'PyType'
```

### Example Code

```Python
from typing import Type, Union

import pydantic

class MyModel(pydantic.BaseModel):
    s: Type[Union[str, bytes]]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
install path: /home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic
python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

### PR DESCRIPTION
**Pull request by JeanArhancet**
## Change Summary

Use `union_schema ` and not `is_subclass_schema` if it's `Type[Union[...]]`

## Related issue number
Resolves #6815 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @adriangb

### CODE REVIEW

**Comment by JeanArhancet** [comment]
please review

**Comment by adriangb** [comment]
I'm not sure that `isinstance` vs ` issubclass` is the issue (although if it is flipped that would be a bug so this PR may make sense anyway).

The bigger issue IMO is that `isinstance` and `issubclass` are not meant to work with parametrized generics and unions. If you do `issubclass(int, int|str)` you get an error and `isinstance(int, int|str)` is False.

I think the best we can do (and what I'm guessing V1 did) is check if the thing inside of `type[...]` is a union and if so convert it to a union of types.

**Comment by JeanArhancet** [comment]
@adriangb I changed the implementation WDYT?

**Review by adriangb — APPROVED** [review]
Looks good to me. While it is not a universal solution this is a relatively common use case and handling it is just a couple lines of code, so it seems worth it to me.

**Pull request merged**
