### PR TITLE
Make sure validated urls pass isinstance checks

### PR DESCRIPTION
**Pull request by sydney-runkle**
Fix issue @alexmojaki reported:

```py
from pydantic import AnyUrl, BaseModel


class MyModel(BaseModel):
    url: AnyUrl


m = MyModel(url='http://test.com/')
print(isinstance(m.url, AnyUrl))  # False
```

With this PR, the last line now prints `True` :)

Update: things aren't working exactly as expected with the new `pydantic-core` changes - working on a new patch there with a fix before we can merge this.

### CODE REVIEW

**Comment by dmontagu** [comment]
Should we only call `source(v)` if `v` is not an instance of `source`?

**Comment by sydney-runkle** [comment]
> Should we only call source(v) if v is not an instance of source?

Good question, yes, I've pushed a fix.

**Review by dmontagu — APPROVED** [review]

**Comment by sydney-runkle** [comment]
I think we need to add a `__dict__` attribute on the `Url` and `MultiHostUrl` classes in `pydantic-core`. Or, we could pass a `cls` instance to `url_schema`. cc @davidhewitt, let's chat about this on Monday!

**Comment by sydney-runkle** [comment]
Looks like there are some more fixes to work on here related to `//` issues - will take a deeper dive this afternoon.

**Comment by sydney-runkle** [comment]
This isn't the way to do this - going to revert the changes in `pydantic-core` and will open a new PR.

I think we can use this as a sort of experiment as a preface to `RustModel`...

**Pull request closed without merging**
