### PR TITLE
Less nested Config hierarchies

### PR DESCRIPTION
**Pull request by gsakkis**
## Change Summary

In case of models that inherit multiple base models, the dynamically generated `Config` creates a deep class hierarchy as [each Config inherits the Config of exactly one base](https://github.com/pydantic/pydantic/blob/1.10.X-fixes/pydantic/main.py#L139). This PR replaces `inherit_config` with a more general `combine_configs` that allows a `Config` to extend multiple bases.

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
sorry not to be more positive, but I think this is the best decision overall.

**Comment by gsakkis** [comment]
No worries, I didn't know that v1.* was in bugfix-only mode.

**Comment by samuelcolvin** [comment]
sorry, yes we're pushing hard to get V2 out asap, hence not making general improvements to V1.

**Comment by gsakkis** [comment]
Big +1 for making config a dict in V2, looking forward to it!

**Pull request closed without merging**
