### PR TITLE
removed excluded fields from __fields_set__ when copying the object

### LINKED ISSUE #4916: `__fields_set__` includes excluded extras on copy
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a model that allows extra fields is copied, excluding an extra field, that field is incorrect included in the new object's `__fields_set__` dictionary which causes problems when attributes are being dynamically retrieved (e.g. https://github.com/PrefectHQ/prefect/issues/8082)

### Example Code

```Python
from pydantic import BaseModel, Extra


class Something(BaseModel, extra=Extra.allow):
    a: int


o1 = Something(a=1, b=2)
assert "b" in o1.__fields_set__, f"'b' should be included in {o1.__fields_set__}"
o2 = o1.copy(exclude={"b"})
assert "b" not in o2.__fields_set__, f"'b' should be excluded from {o2.__fields_set__}"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Jun  1 2022, 06:36:29)  [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by sudouser777**
closes #4916 

1. removed `exclude` fields from `__fields_set__` when copying the object using `copy()` method

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Not sure what this yet, but to consider it we would need linting to pass and to add a test or tests.

**Comment by sudouser777** [comment]
@samuelcolvin added the test cases, can you please check and let me know if any changes required

**Comment by samuelcolvin** [comment]
Thanks so much, merged for completeness, although there's a possibility that we remote `.copy()` in v2.

**Comment by madkinsz** [comment]
Thanks!

**Pull request merged**
