### PR TITLE
Run `pdm add -G settings "pydantic-settings>=2.0b1"`

### PR DESCRIPTION
**Pull request by m9810223**
## Change Summary
Make this command to install `pydantic-settings` with pydantic:
```shell
pip install pydantic[settings]
```

## Checklist

* [ ] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by adriangb** [comment]
@samuelcolvin I personally like this idea. I actually think we should make extras the de-facto way to get `pydantic-settings` or `pydantic-extra-types`, primarily because of the tight coupling between pydantic and these other packages, and because it would give us more flexibility down the road to monorepo them or something like that. We could still keep `pydantic-settings` as it's own PyPi package but declare it as an implementation detail.

What do you think of adding this for now, and if you have any thoughts on making it the recommended approach as described above?

**Comment by lig** [comment]
Usually, extras not just add extra packages but enable additional functionality in the same package. If `pydantic[settings]` would make `pydantic.settings` (notice the dot) working then it seems appropriate. If it just installing additional packages it looks counterintuitive to me.

**Comment by adriangb** [comment]
That's a good point. I would be in favor of `pydantic.settings` for what it's worth, but then it's not as simple of a change as I was thinking, and maybe this PR is not worth it.

**Comment by m9810223** [comment]
I am trying to find some specifications ...
- https://peps.python.org/pep-0508/
- https://peps.python.org/pep-0685/

What I think is, in v1, `BaseSettings` can be imported under `pydantic`.
With installing `pydantic[settings]`, it's easier to import it.

Maybe modifing [_dynamic_imports in pydantic/__init__](https://github.com/pydantic/pydantic/blob/9cfad5c3cee6a31d2bcb410feffff2afc4d0c489/pydantic/__init__.py#L192) is another achievement?

**Pull request closed without merging**
