### PR TITLE
Rename `master` to `main`

### PR DESCRIPTION
**Pull request by hramezani**
## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/pydantic/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hramezani** [comment]
Please review

**Comment by PrettyWood** [comment]
I would wait for v1.10 to be out and rolling before making this change

**Comment by hramezani** [comment]
Fine for me as well

**Comment by samuelcolvin** [comment]
I should probably have waited, but I took the opportunity while we didn't have too many option PRs, probably a mistake.

Anyway, now I've changed it, better to merge this.

**Pull request merged**
