### PR TITLE
feat: allow accessing attributes as strings

### PR DESCRIPTION
**Pull request by dijonkitchen**
## Change Summary

To be less surprising to new users

Ref:
https://stackoverflow.com/a/62561069/5178795

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by dijonkitchen** [comment]
please review

**Comment by hramezani** [comment]
Thanks @dijonkitchen

**Comment by samuelcolvin** [comment]
Hi guys, sorry I didn't see this - I'm not sure about this a good idea.

I don't agree that it's confusing that `my_model['foo']` doesn't work - i think it's confusing that it does work but that pydantic models don't implement the full mapping  interface.

**Comment by dijonkitchen** [comment]
> Hi guys, sorry I didn't see this - I'm not sure about this a good idea.
> 
> I don't agree that it's confusing that `my_model['foo']` doesn't work - i think it's confusing that it does work but that pydantic models don't implement the full mapping interface.

Should they implement the full mapping interface then?

**Comment by samuelcolvin** [comment]
I think it would mostly be confusing, in particular methods little `items()` would conflict with fields.

**Pull request merged**
