### PR TITLE
Remove some cases of test_union_literal_with_other_type

### PR DESCRIPTION
**Pull request by alexdrydew**
## Change Summary

This PR removes two test cases for pydantic-core integration due to the behavior being changed in https://github.com/pydantic/pydantic-core/pull/1132

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by sydney-runkle** [comment]
Assigning this to @davidhewitt, as he'll likely review your other PR once he's back from vacation.

Thanks for your contribution!

**Comment by davidhewitt** [comment]
I don't completely follow why these test cases are no longer wanted? They still seem to contain correct behaviour.

**Comment by alexdrydew** [comment]
> I don't completely follow why these test cases are no longer wanted? They still seem to contain correct behaviour.

This is a case of serialization against `Union[int, Literal['False']]`. The test cases assume that the result depends on the order of the arguments (`False` is serialized to `0` if `int` type is first in the union type arguments list and to `"false"` otherwise). https://github.com/pydantic/pydantic-core/pull/1132 has conflicting changes: resulting value is now depends only on the type of the serialized value.

Honestly, I am not sure how should I handle this case: https://github.com/pydantic/pydantic-core/pull/1132 can't be merged without failing tests either on pydantic-core main or pydantic main (in the case of tests updated to the new behavior)

**Comment by davidhewitt** [comment]
I've merged the pydantic-core PR; the integration tests failing is not a blocker but rather just a signal that things are changing and we need to consider their impact.

For now let's leave this one as-is and when we cut a new `pydantic-core` release and update `pydantic` main I'll see if we need to pull this commit in.

**Comment by davidhewitt** [comment]
Right, now that I've opened #8533 I understand what this was changing. The last commit on that PR addresses these items here; rather than remove them I preferred to just update the test parameters. Many thanks again 👍

**Pull request closed without merging**
