### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by joldicne**
# WARNING!!!

We're currently in the process of rewriting pydantic in preparation for V2, see
https://pydantic-docs.helpmanual.io/blog/pydantic-v2/.

As a result, much of the codebase will change significantly over the coming months.

To avoid wasting your time, please only create Pull Requests if you've got explicit approval by a maintainer.

Otherwise, your pull requests may be closed without review.

Thank you for your interest in pydantic, and your patience. :pray:

**Note:** if you're making a pull request to fix pydantic v1.10, please make it against the `1.10.X-fixes` branch.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi, please can you explain what this is?

Also, please remove the default body and replace it with some explanation.

**Comment by hramezani** [comment]
@joldicne Could you please explain what is this change about?

**Comment by joldicne** [comment]
> 



> @joldicne Could you please explain what is this change about?
> 
> Ah,  you were faster!

This is a case of a real noob mistake on a Monday morning. I thought I was testing on my forked version :(

I hope we can erase any evidence of this ever happening after I close the PR.
Thank you both @hramezani  @samuelcolvin !

**Comment by samuelcolvin** [comment]
no problem, easy mistake to make.

**Pull request closed without merging**
