### PR TITLE
Implemented UTCDatetime constrained type

### LINKED ISSUE #8088: Constrainted datetime based on timezone offset / UTCDateTime
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This is basically the same request as #4385 but that was closed as duplicate of #4330 (which is closed now too) but several things have changed since then so creating a new issue.

Summary of the request: being able to add a constraint on the timezone offset of an AwareDatetime.

Support for constraining the timezone offset was added in pydantic-core in May 2023 with 
 https://github.com/pydantic/pydantic-core/pull/653

So far I can see two ways to achieve this:

- Levering the `tz_constraint` option from pydantic-core by extending from AwareDatetime and overriding `__get_pydantic_core_schema__`,
<details>
  <summary>Example code</summary>

```python
from typing import Any
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel, AwareDatetime
from pydantic_core import core_schema

# Load GetCoreSchemaHandler via try/except because it was made public in v2.4.0
try:
    from pydantic.annotated_handlers import GetCoreSchemaHandler
except:
    from pydantic._internal._annotated_handlers import GetCoreSchemaHandler


class UTCAwareDatetime(AwareDatetime):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        if cls is source:
            # used directly as a type
            return core_schema.datetime_schema(tz_constraint=0)
        else:
            schema = handler(source)
            _check_annotated_type(schema["type"], "datetime", cls.__name__)
            schema["tz_constraint"] = 0
            return schema

    def __repr__(self) -> str:
        return "UTCAwareDatetime"


class TestModel(BaseModel):
    created_at: UTCAwareDatetime


now = datetime.now(tz=timezone(timedelta(seconds=1800)))

model = TestModel(created_at=now)
print(model.model_dump_json())
```

</details>

- Using an `AfterValidator` to do the extra validation
<details>
  <summary>Example code</summary>

```python
from typing_extensions import Annotated
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel, AwareDatetime
from pydantic.functional_validators import AfterValidator


def check_tz(v: datetime):
    assert v.utcoffset() == timedelta(seconds=0)
    return v


UTCAwareDatetime = Annotated[AwareDatetime, AfterValidator(check_tz)]


class TestModel(BaseModel):
    created_at: UTCAwareDatetime


now = datetime.now(tz=timezone(timedelta(seconds=1800)))

model = TestModel(created_at=now)
print(model.model_dump_json())
```
</details>

In both cases there is validation error (as expected), and the error from pydantic-core is superior.

Now back to the future request: Make it easier to use the `tz_constraint` option of pydantic-core to restrict the tz offset of a datetime.
Could be via:
- an extra type? (UTCDatetime? RestrictedTzOffsetAwareDatetime?)
- extend `Field` to support `tz_constraint`?
- ...

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by Zidane786**
## Change Summary
The integration of a `UTCDateTime` constrained type, as mentioned in #8088, allows for validation of whether a given datetime is in the UTC timezone. This is achieved by checking if the offset is 0.

## Related issue number

fix #8088 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by Zidane786** [comment]
please review

**Comment by Zidane786** [comment]
@sydney-runkle can you please review and give some pointers

**Comment by sydney-runkle** [comment]
@Zidane786,

Thanks for your work on this! We're working on getting v2.6 out soon.

I'd love to have this new feature included in v2.7, so I'll give this a thorough review once we get 2.6 out :).

**Comment by sydney-runkle** [comment]
@Zidane786,

Thanks for your work on this. I think the approach that we want to use here is actually adding support for the annotated types `Timezone` constraint, as suggested by @Viicos in this comment: https://github.com/pydantic/pydantic/issues/8088#issuecomment-1807188474.

@samuelcolvin endorsed that suggestion here: https://github.com/pydantic/pydantic/issues/8088#issuecomment-1807207104.

You can see examples of how we've added support for other annotated types annotations such as `Gt` and `Len` throughout the pydantic repo :), ex: https://github.com/pydantic/pydantic/blob/3e871258bd5ea7caa7f18c0b810d8b1e915bd8f2/pydantic/_internal/_known_annotated_metadata.py#L337.

Ping me if you have any follow up questions + when you need a review :). Thanks for your work on this!

**Comment by Zidane786** [comment]
let me take a look, and work on it. Will reach out to you if needed any input from your end. Thank you.

**Comment by sydney-runkle** [comment]
Tidying up PRs -- closing this as stale for now, but we can certainly reopen if it makes sense down the line!

**Pull request closed without merging**
