### PR TITLE
fix main.BaseModel.(dict, json) fields types

### PR DESCRIPTION
**Pull request by shestakovich**
fix main.BaseModel.dict fields (include, exclude, skip_defaults) types
fix main.BaseModel.json fields (include, exclude, skip_defaults) types

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by shestakovich** [comment]
please review

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
Thanks @shestakovich for the patch :+1: 
Please update the patch and fix the same problem in the `main.BaseModel.copy` and `main.BaseModel._iter` functions:

https://github.com/samuelcolvin/pydantic/blob/5606157105d53c1ac4e9e29fd0cee5e04bb74e42/pydantic/main.py#L620-L627

https://github.com/samuelcolvin/pydantic/blob/5606157105d53c1ac4e9e29fd0cee5e04bb74e42/pydantic/main.py#L798-L807

**Review by hramezani — APPROVED** [review]

**Comment by samuelcolvin** [comment]
please update.

**Comment by hramezani** [comment]
@samuelcolvin I think it's ready to merge. What are you waiting for here?

**Comment by samuelcolvin** [comment]
Sorry, I hadn't seen the update, I'll review. please review.

**Comment by samuelcolvin** [comment]
thanks so much for this.

**Pull request merged**
