### PR TITLE
Fix schema references in discriminated unions

### PR DESCRIPTION
**Pull request by adriangb**
Fixes https://github.com/pydantic/pydantic/issues/7611#issuecomment-1735538979 (I hope)

### CODE REVIEW

**Comment by adriangb** [comment]
@Fokko can you try this branch? I tried it locally and can import files I could not before but don't know how to get your unit tests to run (missing env vars, etc.)

**Comment by Fokko** [comment]
@adriangb Thanks for the quick turnaround, this fixed it: https://github.com/apache/iceberg/pull/8646

tnx

**Review by dmontagu — APPROVED** [review]

**Comment by dmontagu** [comment]
I think the following example reproduces the issue that this PR is trying to solve:

```python
from typing import Literal, Annotated

from pydantic import BaseModel, Field, RootModel


class Model1(BaseModel):
    kind: Literal['1'] = '1'
    two: 'Model2 | None'


class Model2(BaseModel):
    kind: Literal['2'] = '2'
    one: Model1 | None


class Root1(RootModel[Model1]):
    pass


class Root2(RootModel[Model2]):
    pass


class Outer(BaseModel):
    first: Annotated[Root1 | Root2, Field(discriminator='kind')]
    second: Annotated[Root1 | Root2, Field(discriminator='kind')]
```

**Comment by Fokko** [comment]
@dmontagu Yes, that looks like it. We use the discriminator to distinguish between the different versions.

**Pull request merged**
