### PR TITLE
Remove defaults filter for namespace

### PR DESCRIPTION
**Pull request by sydney-runkle**
Alternative to https://github.com/pydantic/pydantic/pull/10260 re memory usage.

### CODE REVIEW

**Comment by sydney-runkle** [comment]
With this change:

```
(pydantic_env) (base) programming@sydneys-mbp pydantic % memray stats memray_output3.bin                       
📏 Total allocations:
        2981099

📦 Total memory allocated:
        5.032GB

📊 Histogram of allocation size:
        min: 1.000B
        ---------------------------------------------
        < 4.000B   : 307851 ▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 16.000B  : 615800 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 70.000B  : 457813 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 288.000B : 525727 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 1.163KB  : 634589 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 4.795KB  : 375658 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 19.771KB :  43154 ▇▇
        < 81.511KB :   6267 ▇
        < 336.054KB:  13853 ▇
        <=1.353MB  :    387 ▇
        ---------------------------------------------
        max: 1.353MB

📂 Allocator type distribution:
         MALLOC: 2815062
         REALLOC: 133925
         CALLOC: 31730
         MMAP: 382

🥇 Top 5 largest allocating locations (by size):
        - add_module_globals:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:213 -> 2.028GB
        - push:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_generate_schema.py:339 -> 1.014GB
        - validate_core_schema:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_core_utils.py:570 -> 900.423MB
        - __init__:/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/typing.py:668 -> 348.622MB
        - create_schema_validator:/Users/programming/pydantic_work/pydantic/pydantic/plugin/_schema_validator.py:50 -> 165.853MB

🥇 Top 5 largest allocating locations (by number of allocations):
        - create_schema_validator:/Users/programming/pydantic_work/pydantic/pydantic/plugin/_schema_validator.py:50 -> 1119543
        - validate_core_schema:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_core_utils.py:570 -> 923648
        - complete_model_class:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_model_construction.py:595 -> 478022
        - __init__:/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/typing.py:668 -> 91976
        - get_cls_type_hints_lenient:/Users/programming/pydantic_work/pydantic/pydantic/_internal/_typing_extra.py:238 -> 51607
```

Effectively, reverting https://github.com/pydantic/pydantic/pull/10136, which increased memory usage + didn't simplify debugging all that much.

**Comment by sydney-runkle** [comment]
One question - do we need to copy the `f_locals` here? If we were being ultra safe, I think the answer is yes. But I don't know if that's actually necessary based on how we handle the namespace.

**Comment by Viicos** [comment]
Seems like this also improve performance.

> One question - do we need to copy the `f_locals` here? If we were being ultra safe, I think the answer is yes. But I don't know if that's actually necessary based on how we handle the namespace.

We don't do any mutations on the types namespace so I don't think we should introduce any extra overhead.

**Review by samuelcolvin — APPROVED** [review]
I think this looks good.

@sydney-runkle can you add a comment explaining why we're not copying or `f_locals` and that it must not be mutated.

We could return `Mapping[str, Any]` then have implement our own `FrozenMapping` type that holds `frame.f_locals` internally but stops it being accidentally modified, but maybe that's over kill.

@davidhewitt maybe you should look at this too.

**Review by Viicos — APPROVED** [review]

**Pull request merged**
