### PR TITLE
docs: add common mistakes section

### LINKED ISSUE #8380: Common mistakes docs section
Many of the issues we get are repeats of the same common questions / mistakes. We should create a small docs section logging said common mistakes and their solutions :).

### PR DESCRIPTION
**Pull request by bL34cHig0**
## Change Summary
This PR adds a page under the `Examples` section to log common mistakes/questions and their solutions.  The main purpose of this is to address common `mistakes` and/or `questions` that are duplicates in the repository **Issues** tab. 

## Related issue number
fixes #8380

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @samuelcolvin

### CODE REVIEW

**Comment by bL34cHig0** [comment]
@sydney-runkle 

Please review the task done so far. Thank you :)

**Comment by sydney-runkle** [comment]
@bL34cHig0,

I don't see any changes in the 'files changed' tab that are significant...

**Comment by bL34cHig0** [comment]
> @bL34cHig0,
> 
> I don't see any changes in the 'files changed' tab that are significant...

Oh my bad. I'll push the updates again.

**Comment by bL34cHig0** [comment]
> @bL34cHig0,
> 
> I don't see any changes in the 'files changed' tab that are significant...

@sydney-runkle 

How about now? The changes should be visible now.

Thanks 👍

**Comment by sydney-runkle** [comment]
@bL34cHig0,

Thanks for your work on this! I have a few other examples that I'd like to add - I'll take that on later this week. Great work 🚀 !

**Comment by bL34cHig0** [comment]
> @bL34cHig0,
> 
> Thanks for your work on this! I have a few other examples that I'd like to add - I'll take that on later this week. Great work 🚀 !


> @bL34cHig0,
> 
> Thanks for your work on this! I have a few other examples that I'd like to add - I'll take that on later this week. Great work 🚀 !

@sydney-runkle 

Thank you for reviewing and I'll be waiting on the other examples. I'll be adding this [example](https://github.com/pydantic/pydantic/issues/8708) too.

**Comment by sydney-runkle** [comment]
@bL34cHig0,

After thinking about this more, I think it makes more sense to specifically elaborate on each of these issues within their own relevant docs section. It feels like having a catch-all FAQ is more a reflection of poor documentation than it is helpful.

That being said, I do think the work that you've done is useful, so I'm going to attach your changes to the original issue for others to use as a reference in the future :). I'm also going to take snippets of your work + apply them to the relevant docs sections to make sure that we're being clear about those FAQs in the relevant sections :).

Thanks for all of your great work here!

**Comment by bL34cHig0** [comment]
@sydney-runkle 

Sure, I totally concur with this idea. Adding each individual solution (in-depth) to the relevant section of the docs will go a long way.

**Pull request closed without merging**
