### PR TITLE
⚡️ Speed up `is_pydantic_dataclass()` by 41% in `pydantic/dataclasses.py`

### PR DESCRIPTION
**Pull request by misrasaurabh1**
### 📄 `is_pydantic_dataclass()` in `pydantic/dataclasses.py`

📈 Performance improved by **`41%`** (**`0.41x` faster**)

⏱️ Runtime went down from **`4.80 microseconds`** to **`3.40 microseconds`**
### Explanation and details

Here's the optimized version of the provided program.

### Explanation.
1. **Short-circuit Evaluation:** I reordered the conditions in the `return` statement to utilize short-circuit evaluation. The check for `'__pydantic_validator__' in class_.__dict__` is less expensive and will fail fast if `class_` is not a valid type with this attribute, reducing unnecessary calls to the relatively more expensive `dataclasses.is_dataclass` function.
  
2. **Error Handling:** Added a `try-except` block to quickly handle the scenario where `class_` may not have the `__dict__` attribute (`__dict__` is not present for some objects that do not have attribute dictionaries). This prevents the function from throwing an attribute error and failing incompletely.

This should make the function slightly faster, especially when dealing with objects that early out on the `__dict__` check.

### Correctness verification

The new optimized code was tested for correctness. The results are listed below.
#### ✅ 211 Passed − ⚙️ Existing Unit Tests
<details>
<summary>(click to show existing tests)</summary>

```python
- test_dataclasses.py

```
</details>

## Checklist

* [X] The pull request title is a good summary of the changes - it will be used in the changelog
* [X] Unit tests for the changes exist
* [X] Tests pass on CI
* [X] Documentation reflects the changes where applicable
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by sydney-runkle** [comment]
@misrasaurabh1,

How about:

```py
if hasattr(class_, '__dict__'):
    return '__pydantic_validator__' in class_.__dict__ and dataclasses.is_dataclass(class_)
return False
```

What are the performance changes like with that approach?

**Comment by misrasaurabh1** [comment]
Great suggestion, when I tested your recommendation with codeflash on my laptop, I got a 23% speedup. But when I try the try/except approach (the one that codeflash originally recommended), I got a 36% speedup. So the try/except approach seems to be faster.

**Comment by sydney-runkle** [comment]
> Great suggestion, when I tested your recommendation with codeflash on my laptop, I got a 23% speedup. But when I try the try/except approach (the one that codeflash originally recommended), I got a 36% speedup. So the try/except approach seems to be faster.

Awesome, thanks for looking into this. We're happy with the existing change, then!

I'll note, this isn't a super critical function to speed up, but we'll take the performance benefit where we can get it :). We're excited to collaborate more on more critical functions!

**Review by sydney-runkle — APPROVED** [review]
Looks great! Thanks folks!

**Pull request merged**
