### PR TITLE
Include types during model equality check

### PR DESCRIPTION
**Pull request by JacobHayes**
Currently, `BaseModel.__eq__` only considers the _dict_ representation of the two models. This leads to incorrect (imo) equality for models of different types but the same fields. For example (not contrived, ~real code I wrote):

```python3
from pydantic import BaseModel

class Type(BaseModel):
    description: str = ""
    class Config:
        frozen = True  # Only relevant for hash comparison below

class Int8(Type):
    pass

class Int16(Type):
    pass

# then...

>>> i8, i16 = Int8(), Int16()
>>> i8 == i16
True
>>> hash(i8) == hash(i16)
False
```

## Change Summary

This PR adds the model classes into the equality check to distinguish on type+content. Note that this new behavior more closely matches `__hash__` (for frozen models), which mixes the class + the values (not sure why the keys aren't included :shrug:)

@samuelcolvin suggests a very similar change in https://github.com/samuelcolvin/pydantic/issues/1494#issuecomment-630144720. I avoided most of the "breaking change" described there - we're still converting the models to dicts. However, the class check may still be a breaking change for some esoteric uses, including 1 (fixed) test: `test_generic_recursive_models`, which was arguably incorrect in the first place (comparing an instance with the TypeVar against one without).

## Related issue number

Tangentially: #1494

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by JacobHayes** [comment]
If this extra `__eq__` check makes sense, please review when you have a minute @PrettyWood! 🙇

**Comment by JacobHayes** [comment]
Hmm, this works fine for simple models, but doesn't work on nested ones as they are just turned into and compared as dicts.

Any suggestions on how that should be handled?

**Comment by PrettyWood** [comment]
@JacobHayes I agree the current behaviour of `__eq__` is not always desired.
Personally I overwrote it on one of my project where I rely on it with
```py
    def __eq__(self, other: Any) -> bool:
        return self.__class__ == other.__class__ and tuple(self._iter()) == tuple(other._iter())
```
This is more consistent with `dataclass` (and `pydantic.dataclass`!) behaviour.
But this change needs some work because it breaks some stuff with generics and custom types.
And most importantly it will probably break some code for endusers that "don't care" about types and just want to compare the content.
Quite a lot of people want pydantic to be stricter but at the same time the "looseness" of it is one of its strength 🤷

**Comment by JacobHayes** [comment]
Thanks for the snippet, I'll use your simpler one! I was about to suggest a page like the old [`flask` snippets](https://web.archive.org/web/20170608150532/http://flask.pocoo.org/snippets), but looks like they decided otherwise and deleted it. 😁

As you note on the breaks, do you think it best to just close this PR (fine with me)? I've seen some other talk about having a strict flag (and doing so here actually seems easy enough), but maybe that also falls into too much complexity for a relatively simple override.

**Comment by PrettyWood** [comment]
I honestly think it would make sense for v2.
The current behaviour with `dict` comparison is even simpler to overwrite and this "loose" way of checking equality could be done by people who actually rely on it.

**Comment by sveinugu** [comment]
Ran into this issue in my use case, and wanted to ping it. As mentioned above, I believe the Python standard is to include class equality in an equality check, and I think the opposite behaviour (only considering data content) is confusing and non-intuitive. The comparison to `dataclass` is a good example of this.

I also wanted to add another argument for implementing this in v2:

It has been a long-contented issue whether what pydantic does should be described using the term "parse" or "validate" (see https://github.com/pydantic/pydantic/issues/578). I see in the [v2 blog post](https://docs.pydantic.dev/blog/pydantic-v2/#im-dropping-the-word-parse-and-just-using-validate) that the issue will finally be settled, and "validate" is the winner. I am not very happy with this conclusion (and it also seems @samuelcolvin was not fully satisfied with this conclusion either, according to the smiley), but that is another issue and the ship has sailed for that one, I believe. (Granted, I did find pydantic myself by googling "python validation library" or similar, so there are at least practical arguments for this.)

I believe the main arguments for using the term "parse" can be most easily grasped by reading the influential blog post ["Parse, don't validate"](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) by Alexis King (which I btw discovered from a comment in the above-mentioned issue: https://github.com/pydantic/pydantic/issues/578#issuecomment-626575276). So the main point of this concept (also termed "type-driven development") is to parse data once according to the required model and then let this added information (that the data now adheres to the model) be stored/remembered by the data type. In that way, you would not need to validate the data ever again in your code base.  [Btw: adding a section on this in the pydantic docs would be awesome and a way to not fully cave in to the "validate" crowd! :) ]

Consequently, if one wants to use pydantic as the vessel for "type-driven design", the model itself is important for downstream logic, not only the parsed data. Hence, I think it would be natural for __eq__ to consider also include the data types in the checks.

The main counter-argument is, I assume, that lots of existing code (and especially tests) will start failing if this is added, so if this is to be changed, v2 at least seems the proper place to do it.

I believe the best solution would be to add a config flag to enable/disable this behaviour (as mentioned above: https://github.com/pydantic/pydantic/pull/3066#issuecomment-894636366). However, I don't think this should be the same as the `strict` flag, as one would probably not set `strict` to `True` if following the "type-driven design" concepts. One could argue that checking types in equality tests should be the default if `strict=False`, however this seems counter-intuitive on a semantic level, as the equality check itself is actually more strict in this case. So a `include_types_in_equality` (or better-worded version) is probably the best solution, IMO. It also follows the [zen of Python](https://peps.python.org/pep-0020/) ("explicit is better than implicit").

I would also argue for `include_types_in_equality` being set to `True` as default for v2, as `strict` is by default set to `False` (I believe).

**Comment by dmontagu** [comment]
Revisiting this in v2; I think there are a few pieces of state beyond `__dict__` that we may want to check for equality (beyond the type, which I agree should match). In particular, you can see essentially the full object state information here:

https://github.com/pydantic/pydantic/blob/83b3c49e99ceb4599d9286a3d793cea44ac36d4b/pydantic/main.py#L245-L251

This includes `__dict__`, but also `__fields_set__` and `__private_attrs__`.

Currently, I am thinking we should have `__eq__` look for matches on `__dict__` and `__private_attrs__`, but _not_ `__fields_set__`. Would anyone object to that? @samuelcolvin let me know if I should create a separate issue for this.

An additional concern: If we do matching on type, there are some nuisances with equality checks for generics with different parametrizations. In particular, note the following behavior:

```python
T = TypeVar("T")
S = TypeVar("S")
class MyModel(BaseModel, Generic[T]):
    x: T
assert MyModel[T] is MyModel
assert MyModel[S] is not MyModel  # a subclass is created because S != T
```
Therefore, you could end up with:
```python
MyModel[S](x=1) != MyModel[T](x=1)  # due to type inequality
```
I don't think this inequality is meaningful, but I also am not super keen to go down the rabbit hole of ensuring we get exact type equality if you reparametrize a type with a single typevar (I expect this would wreak some havoc on the current approach to resolving recursive generic types, and I really don't want to revisit that without a better reason than this edge case.)

I am open to opinions about how to resolve the generic types equality issue (or to just leave it unresolved).

(Note that currently, `MyModel[int, str] != MyModel[int, T][str]`, but I think the caching implementation can be improved to fix this, so I'm less concerned about this as a source of equality misbehavior. I think it will be harder to resolve with generics that are re-parametrized with different typevars though.)

**Pull request closed without merging**
