### PR TITLE
Fix typos in docstring

### PR DESCRIPTION
**Pull request by der-gabe**
## Change Summary

Fix two tiny typos in the docstring for `get_flat_models_from_fields` in `pydantic/schema.py`.

## Related issue number

None

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] ~Unit tests for the changes exist~ – unnecessary in the absence of code changes
* [ ] ~Tests pass on CI~ – unnecessary in the absence of code changes
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @hramezani

### CODE REVIEW

**Comment by der-gabe** [comment]
please review

**Review by sydney-runkle — APPROVED** [review]
Amazing, thank you :)

**Comment by hramezani** [comment]
There was a PR for the main branch that I closed because it touched a file in V1. 
Just reopened it and assigned to you @sydney-runkle 
https://github.com/pydantic/pydantic/pull/8323

**Comment by sydney-runkle** [comment]
@der-gabe,

Closing as stale for now. Feel free to ping us when you've pulled in main to fix the docs build and we can merge this!

**Pull request closed without merging**
