### PR TITLE
Update to Ruff `0.4.8`

### PR DESCRIPTION
**Pull request by Viicos**
## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Review by sydney-runkle — COMMENTED** [review]
Just looked through all of the files - changes look great, thanks @Viicos!

We'll want to get the `mypy` tests back to passing though, so might have to revert those changes...

**Comment by sydney-runkle** [comment]
Once we get those back to passing, I'll approve :).

**Comment by sydney-runkle** [comment]
Ah ok so the annoying thing with these is that we have to run the mypy tests locally and match up the output files with the newly formatted input files. I'll do that and push shortly :).

**Comment by sydney-runkle** [comment]
For some reason I can't repro the linting failures locally...

**Comment by sydney-runkle** [comment]
Chatted with @dmontagu,

I believe all of the `mypy` output files that have been removed are not necessary - these changes were applied by rerunning all of the mypy tests locally with help from the `make` commands.

**Review by sydney-runkle — APPROVED** [review]

**Comment by Viicos** [comment]
@sydney-runkle thanks for finishing this one!

**Pull request merged**
