### PR TITLE
Add Migration Guide page

### PR DESCRIPTION
**Pull request by tpdorsey**
Adds a migration guide to the docs

## Change Summary

* New Migration Guide page
* Move alpha installation and migration notes from blog post to Migration Guide

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by tpdorsey** [comment]
@adriangb the AnalyzedType example is not passing tests, what can we do to fix that up?

**Comment by adriangb** [comment]
I'll fix it this afternoon. Wasn't it already running (and passing)?

**Comment by adriangb** [comment]
(sorry fat fingered the button)

**Comment by adriangb** [comment]
> @adriangb the AnalyzedType example is not passing tests, what can we do to fix that up?

fixed

**Comment by adriangb** [comment]
@tpdorsey this is copied from the blog post right? If so let’s merge and iterate since it’s been reviewed in depth already.

**Pull request merged**
