### PR TITLE
Add note about Pipeline API recommended usage

### PR DESCRIPTION
**Pull request by adriangb**
I think it's important to make this clarification. Without it I fear people may get excited about the shiny new thing or go too wild with it just because of how much it can do, which IMO would be a mistake. I view this as an advanced feature, like descriptors or something: when you need it it's awesome it's there and saves you a lot of pain, but use it everywhere for everything and you'll end up with a spaghetti codebase that's hard to navigate and reason about.

Happy to word this comment differently or even give a concrete example of what I mean by `UserIn` and `UserOut`.

### CODE REVIEW

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Thanks for adding this note. I'm also in the process of solidifying some of our docs before the official release, so I'm super happy to see this addition as well. 2 things:

1. Let's elaborate on the `UserIn` and `UserOut` patterns
2. Can you say "the following" example, just for clarity

Thanks!

**Comment by adriangb** [comment]
Added an example

**Review by sydney-runkle — APPROVED** [review]
This looks good. I think we should take another pass at expanding these docs if/when we decide to move this feature out of its experimental stage, as mentioned in the TODO above.

I think this example helps to illustrate that there's often value in slightly more verbose code when it comes to readability and maintainability.

Thanks @adriangb!

**Comment by sydney-runkle** [comment]
Happy to merge once we fix CI :)

**Pull request merged**
