### PR TITLE
Add support for `re.Pattern`

### PR DESCRIPTION
**Pull request by hramezani**
## Change Summary

Add support for `re.Pattern`

## Related issue number
ref https://github.com/pydantic/pydantic/issues/4360
This PR just address the `re.pattern`

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/pydantic/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Review by PrettyWood — APPROVED** [review]
LGTM!

**Review by Bobronium — CHANGES_REQUESTED** [review]
This doesn't include changes to schema generation, mentioned in #4360. 
https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/schema.py#L805


 So generating schema with re.Pattern most likely gonna blow up.

**Comment by hramezani** [comment]
> This doesn't include changes to schema generation, mentioned in #4360.
> 
> https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/schema.py#L805
> 
> So generating schema with re.Pattern most likely gonna blow up.

I've checked this as well but it seems we don't need it because the `lenient_issubclass(field_type, type_)` returns `True` for `re.Pattern`

**Review by samuelcolvin — COMMENTED** [review]
Let's add a test for schema, just to be sure.

Also Please remember "fix #xxx" in the PR body, I won't always remember to update it.

please update.

**Comment by hramezani** [comment]
> Let's add a test for schema, just to be sure.

The test for the schema is part of  [test_pattern](https://github.com/pydantic/pydantic/pull/4366/files#diff-bd467a363c9f155a2e6a7716aeca0c351089135a53d09a66138cea4f16506ebdR2544)

> Also Please remember "fix #xxx" in the PR body, I won't always remember to update it.

I didn't add `fix` because this PR just add `re.Pattern` and the issue is about adding `re.Pattern` and `type` support. I am going to create another PR for `type` later. I don't want to close the issue after we merge this one.

**Comment by samuelcolvin** [comment]
Good point, sorry my mistake.

**Comment by hramezani** [comment]
please review

**Review by Bobronium — APPROVED** [review]

**Comment by samuelcolvin** [comment]
thanks so much.

**Pull request merged**
