### PR TITLE
Move settings to `pydantic-settings`

### PR DESCRIPTION
**Pull request by samuelcolvin**
Removing settings from pydantic as settings will be a separate package `pydantic-settings`.

We might make it installable via `pydantic[settings]`, not sure yet if this is a good idea?

skip change file check.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Unfortunately we have a slight problem - someone has already taken the package name [`pydantic-settings`](https://pypi.org/project/pydantic-settings/), I've emailed them asking if they could change their package name.

**Comment by samuelcolvin** [comment]
otherwise should be ready.

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
> Unfortunately we have a slight problem - someone has already taken the package name [`pydantic-settings`](https://pypi.org/project/pydantic-settings/), I've emailed them asking if they could change their package name.

Do you have other options in your mind?

**Comment by samuelcolvin** [comment]
He has replied and kindly agreed to release the name, he's just getting his 2fa reset.

**Comment by PrettyWood** [comment]
> He has replied and kindly agreed to release the name, he's just getting his 2fa reset.

Great!

--------------

According to the description of author's package

> but from my point it’s missing some useful features:
> - Overriding settings values by environment variables even for nested fields
> - Providing detailed information about value location inside a loaded file or environment variable, which helps to point user mistake
> - Documenting model fields isn’t feels comfortable, but it’s really essential to write comprehensive documentation for application settings

I reckon it'd be great to work together with author on the future of (official) `pydantic-settings`

**Comment by samuelcolvin** [comment]
Ye, I'd love him to contribute, he says he has no plans to continue to work on the package though.

But maybe joining the team here will tempt him 😉.

**Comment by samuelcolvin** [comment]
See https://github.com/pydantic/pydantic-settings, I've moved the existing logic to a new package.

**Comment by caniko** [comment]
+1 for `pyndatic[settings]`

**Comment by Ovsyanka83** [comment]
@samuelcolvin you probably already know this but better be safe than sorry:

If the person does not reply or does not want to give you the package, you can try filling out a PEP 541 request [here](https://github.com/pypa/pypi-support/issues).

**Comment by ofek** [comment]
Can we look into finally supporting this? 🙂 https://github.com/pydantic/pydantic/issues/1676

**Comment by samuelcolvin** [comment]
> Can we look into finally supporting this? 🙂 #1676

Yea definitely, V2 is an opportunity to fix all the messy stuff we couldn't fix in minor releases.

**Comment by ofek** [comment]
https://github.com/pydantic/pydantic-settings/issues/1

**Comment by danields761** [comment]
@Ovsyanka83, relax, I'll transfer pypi name via my good will, and Samuel didn't sent me any blackmails ;)

@PrettyWood , nice to hear that! If some of my original ideas could be integrated into new pydantic-settings, I'll gladly contribute

@samuelcolvin , is there features of mine pydantic-settings library, which you would like to pull into new one?

**Comment by Ovsyanka83** [comment]
@danields761 I apologize :)

I was writing this in case the package was name-squatted by someone. Thanks for transferring it!

**Comment by samuelcolvin** [comment]
@danields761, thanks so much.

Yes, I think so. Like @PrettyWood said, we definitely want to have better support for environment variables filling nested fields.

I also think it would be really useful to provide details on where field are populated from as you mention.

But I need to go through this in more depth and write a proposal, please keep your `pydantic-settings` repo in place so I can review it further while writing the proposal.

**Comment by samuelcolvin** [comment]
Oh, forgot to add @danields761, hapy to make you a collaborator on the `pydantic/pydantic-settings` repo if you'd like.

**Comment by danields761** [comment]
@samuelcolvin , that would be nice, thanks!

Please, let me know, when you'll be ready

**Comment by danields761** [comment]
@samuelcolvin , that would be nice, thanks!

Please, let me know, when you'll be ready

**Comment by samuelcolvin** [comment]
Thanks @danields761, I've sent you an email.

**Comment by hmeine** [comment]
FWIW, I have been using https://github.com/danields761/pydantic-settings/ mostly for its `with_attrs_docs` decorator.

It greatly reduces the visual noise / clutter when documenting fields that otherwise do not even need a `Field()`.

Hence, I would love to see this come upstream (not caring so much about the actual syntax / import).

**Comment by samuelcolvin** [comment]
Thanks @hmeine, could you create an issue on https://github.com/pydantic/pydantic-settings so we don't forget this.

**Comment by maartenbreddels** [comment]
> We might make it installable via `pydantic[settings]`


This could have made it possible to make libraries compatible with pydantic 1 and 2. Now we need to add the following requirement:
 * `"pydantic-settings; python_version > '3.6'",`

Which makes our libraries implicitly dependent on pydantic 2.

If we could add `pydantic[settings]`, pip would just ignore it for pydantic 1 (ok, it gives a warning, but it makes it possible for users to still install pydantic 1 is needed for some reason).

See also https://github.com/pydantic/pydantic/discussions/6497

**Pull request merged**
