### PR TITLE
Handle validators on vanilla dataclass fields

### PR DESCRIPTION
**Pull request by dmontagu**
Partially addresses #5271.

Still need to add a test or two, but opening the PR now so work doesn't end up duplicated.

See https://github.com/pydantic/pydantic/issues/5271#issuecomment-1561832416 for at least one test we can add.

### CODE REVIEW

**Comment by dmontagu** [comment]
@adriangb If you are totally against this change we can leave it, but if you'd just want to see other tests pass first, I'm open to any suggestions.

**Review by adriangb — APPROVED** [review]

**Comment by adriangb** [comment]
If you feel confident that this doesn't break under edge cases then let's go for it

**Comment by dmontagu** [comment]
I wouldn't say confident, but it _seems_ sound to me. I'll give a bit more thorough review of where we construct schemas related to dataclasses before merging.

@adriangb there's nothing similar with TypedDict now is there? I think we can't do serializers/validators as methods on those (in not-small-part related to inability to inspect class hierarchy), just making sure though.

**Comment by adriangb** [comment]
It should work for TypedDict on the latest typing-extensions version and Python 3.12.

**Pull request merged**
