### PR TITLE
Fix recursion error in json schema generation

### LINKED ISSUE #6708: Leak in `pydantic_js_functions` leading to `RecursionError`s with V2 generic model json schema handling
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There seems to be a leak related to items in `pydantic_js_functions` which also leads to an `RecursionError` with `model_json_schema` handling. Seems `pydantic_js_functions` is getting lot of entries to the list with certain types of generic models. Below I tried to isolate the problem as best as possible but there might be even a simpler example of the failure.

### Example Code

```Python
from typing import Generic, Optional, TypeVar

from pydantic import BaseModel

try:
    # v2
    from pydantic._internal._generics import _GENERIC_TYPES_CACHE
    from pydantic import BaseModel as PydanticModel
    GenericModel = BaseModel
except ImportError:
    # v1
    from pydantic import BaseModel
    from pydantic.generics import GenericModel as GenericModel


T = TypeVar("T")


def test_leak():
    class Inner(BaseModel):
        a: int

    class Outer(GenericModel, Generic[T]):
        b: Optional[T]  # Works when not Optional...

    for i in range(1000):
        class ModelTest(BaseModel):
            c: Outer[Inner]

        if core_schema := getattr(ModelTest, "__pydantic_core_schema__", None):
            # v2
            # pydantic_js_functions on "Inner" keeps on growing at each iteration: 5, 6, 7, 8, 9, 10...
            inner = next(d for d in core_schema["definitions"] if d["cls"].__name__ == "Inner")
            inner_pydantic_js_functions = inner["metadata"]["pydantic_js_functions"]
            print(f"Run {i}: len(pydantic_js_functions)={len(inner_pydantic_js_functions)}")
            # ... and then RecursionError at "Run 228: len(pydantic_js_functions)=232"
            ModelTest.model_json_schema()
        else:
            # v1
            # It works without issues
            ModelTest.schema()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/markussintonen/Library/Caches/pypoetry/virtualenvs/leak-test-VvUvdXxD-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Dec 23 2022, 09:40:27) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #6708

Selected Reviewer: @Kludex

### CODE REVIEW

**Comment by adriangb** [comment]
@commonism any concerns with this?

**Review by Kludex — APPROVED** [review]

**Review by dmontagu — COMMENTED** [review]
I think this makes sense, though @adriangb and I both agree that there is probably a better fix out there.

Probably the best way to fix it would be to generate the JSON schema more fully-independently of the core schema, rather than storing JSON-modification functions on the core schema. Or at least rework the core schema generation so that there is less mutability. But this works now.

**Comment by MarkusSintonen** [comment]
@adriangb amazing thank you for the quick fix! I tested this branch against some of our code which failed previously with random RecursionErrors and now it works with this branch changes

**Comment by commonism** [comment]
> @commonism any concerns with this?

No.

**Pull request merged**
