### PR TITLE
added mention of computed_field in model_dump usage explanation

### PR DESCRIPTION
**Pull request by berzi**
## Change Summary

Adds a mention of computed fields under the usage notes for `model_dump`, which is where I would have liked to know about it.

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @dmontagu

### CODE REVIEW

**Comment by berzi** [comment]
Documentation-only change, no tests needed. Please review.

**Comment by Viicos** [comment]
Context: https://github.com/pydantic/pydantic/discussions/7558

**Comment by hramezani** [comment]
Thanks @berzi for creating this patch 🙏 

As you may know, we refactored the Pydantic documentation. and `docs/usage/serialization.md` move to `docs/concepts/serialization.md`.

Also, `computed_field` documentation has been moved to `api/fields.md#pydantic.fields.computed_field`.

Please update

**Comment by sydney-runkle** [comment]
Closing in favor of the updated PR I added that accounts for the docs refactor. Thanks for the contribution @berzi and the help @Viicos!

**Pull request closed without merging**
