### PR TITLE
Add support `re.Pattern[str]` to `pattern` field

### LINKED ISSUE #9052: Add support `re.Pattern[str]` to `pattern` field in `Field`
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I think it just a simple idea about using already compiled regexp to set in `pattern` field.

Example:

```python diff
import re

from pydantic import BaseModel, Field

TOKEN_RE = re.compile(r"glpat-.{20}")


class ModelWithToken(BaseModel):
    """Token model with secret."""

    token: SecretStr = Field(pattern=TOKEN_RE)  # Instead of `pattern=TOKEN_RE.pattern`
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by jag-k**
## Change Summary

I think it just a simple idea about using already compiled regexp to set in `pattern` field.

Example:

```python diff
import re

from pydantic import BaseModel, Field

TOKEN_RE = re.compile(r"glpat-.{20}")


class ModelWithToken(BaseModel):
    """Token model with secret."""

    token: SecretStr = Field(pattern=TOKEN_RE)  # Instead of `pattern=TOKEN_RE.pattern`
```

## Related issue number

fix #9052

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist — I don't think we need tests for this
* [x] Tests pass on CI
* [ ] Documentation reflects the changes where applicable — I don't think we need docs for this
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @davidhewitt

### CODE REVIEW

**Comment by jag-k** [comment]
please review

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
Looks great, would be helpful to add some tests! Thanks!

**Comment by sydney-runkle** [comment]
@jag-k, ping!

**Comment by jag-k** [comment]
> @jag-k, ping!

@sydney-runkle Sorry to keep you waiting. I missed your message a bit in the mail.

I added tests. Tell me, is everything okay with them?

**Review by sydney-runkle — APPROVED** [review]
Looks great, thanks for your work on this!

**Pull request merged**
