### PR TITLE
Improve test coverage of pydantic._internal._core_utils

### PR DESCRIPTION
**Pull request by hramezani**
Not sure these tests are relevant. It might be better to move this function to `pydantic-core`

Selected Reviewer: @lig

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Comment by lig** [comment]
please update

**Comment by hramezani** [comment]
please review

**Comment by hramezani** [comment]
> Should we be testing private modules like this, tho?
> 
> I'd think that we want to reach that part of the code via public API, which would also allow us more freedom to change underneath implementation (if needed). 🤔

Yeah, Best way is to reach that part via public API. but it's hard or maybe not possible. That's why we don't have coverage for some lines of these functions.

As I mentioned in PR description, we might need to move them to `pydantic-core` because these test make much more sense there

**Comment by Kludex** [comment]
Based on your previous comment... Should we then add those tests here? Alternatively, we can add pragmas, and create an issue on `pydantic-core`s side.

**Review by lig — APPROVED** [review]

**Pull request merged**
