### PR TITLE
Remove allOf JSON schema workarounds

### LINKED ISSUE #6343: Remove `'allOf' JSON schema workarounds
https://github.com/pydantic/pydantic/pull/6336#issuecomment-1615801492

Selected Assignee: @hramezani

### PR DESCRIPTION
**Pull request by dpeachey**
## Change Summary

The JSON schema spec was updated to allow sibling keys alongside `$ref` keys so it is no longer required to wrap the `$ref` key in a `allOf` array with a single `$ref` element. This change removes the `allOf` workarounds.

## Related issue number

fix #6343 

## Checklist

* [X] The pull request title is a good summary of the changes - it will be used in the changelog
* [X] Unit tests for the changes exist
* [X] Tests pass on CI
* [X] Documentation reflects the changes where applicable
* [X] My PR is ready to review

### CODE REVIEW

**Comment by dpeachey** [comment]
Hi,

`fastapi` test for OpenAPI schema format failed which is to be expected since the output is changing, however I don't know what to do about this :) Could someone advise?

Thanks,

Dan

**Comment by sydney-runkle** [comment]
Exciting stuff! Let's wait for @adriangb to review this on Monday - he's pretty familiar with this part of the codebase :).

**Comment by dmontagu** [comment]
I'll note that I am in favor of this change, and my experience has been that many/most existing tools that interop with JSON schema behave as expected when sibling keys to a `$ref` exist, even though they were designed at a time when that wasn't allowed.

However, just as part of appropriate due diligence — can you share a reference that this is now allowed in JSON schema? In particular, I'm thinking we may need to reference a new draft version or similar.

The FastAPI test failures can be white-listed if we want to move forward with this, there is an existing pattern for that I can dig up if there are no white-listed tests currently.

**Comment by sydney-runkle** [comment]
I believe this might be what we're looking for: https://json-schema.org/draft/2019-09/release-notes#core-vocabulary

**Review by sydney-runkle — APPROVED** [review]

**Comment by sydney-runkle** [comment]
@tiangolo, just wanted to notify you re this change, given that it broke one of the fastapi integration tests 👍

**Pull request merged**
