### PR TITLE
Make detection of TypeVar defaults robust to the CPython PEP-696 implementation

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Change Summary

When implementing PEP 696 (default values for TypeVars, ParamSpecs and TypeVarTuples, we decided to implement the PEP slightly differently from the prototype that existed in `typing_extensions`. Specifically:
- With the old implementation in `typing_extensions`:
  - If you passed `default=None` when constructing a TypeVar, the `__default__` attribute would be set to `types.NoneType`
  - If you did not pass a value to the `default=` parameter, the `__default__` attribute would be set to `None`
- With the new implementation in CPython:
  - If you pass `default=None` when constructing a TypeVar, the `__default__` attribute is set to `None`
  - If you do not pass a value to the `default=` parameter, the `__default__` attribute is set to the new sentinel object `typing.NoDefault`.
- The new implementation at CPython also has added a new `has_default()` method to TypeVars, ParamSpecs and TypeVarTuples

I backported these changes to the `typing_extensions` implementation of PEP 696 yesterday, and we realised today that it breaks some tests over at pydantic: https://github.com/python/typing_extensions/issues/381. This PR fixes the tests so that they work if you're using a released version of `typing_extensions`, but they also work with the CPython implementation of PEP 696 and with the `typing_extensions` main branch.

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I tested this locally by making this change to `pyproject.toml`:

```diff
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -46,7 +46,7 @@ classifiers = [
 ]
 requires-python = '>=3.8'
 dependencies = [
-    'typing-extensions>=4.6.1',
+    'typing-extensions @ git+https://github.com/python/typing_extensions.git',
     'annotated-types>=0.4.0',
     "pydantic-core==2.18.2",
 ]
```

And then rerunning `make install`, then `make`. The tests continued to pass using the `main` branch of `typing_extensions`.

**Comment by AlexWaygood** [comment]
please review

**Review by JelleZijlstra — APPROVED** [review]
This looks correct to me. The `try` branch would be taken on Python 3.13+ and future versions of typing-extensions.

**Comment by AlexWaygood** [comment]
This PR should fix the "test typing-extensions main" job in pydantic's CI, which is currently failing on your `main` branch (e.g. see the test failures on https://github.com/pydantic/pydantic/pull/9431)

**Review by sydney-runkle — APPROVED** [review]
@AlexWaygood,

Thanks so much for this fix! @JelleZijlstra, thanks a bunch for the review!

**Comment by sydney-runkle** [comment]
@AlexWaygood,

Before we merge, could you please add some tests for the behavioral changes you've listed above? Thanks again!

**Comment by AlexWaygood** [comment]
> @AlexWaygood,
> 
> Before we merge, could you please add some tests for the behavioral changes you've listed above? Thanks again!

Sure -- what kind of tests are you looking for? This fixes the failing CI job on `main` that tests with the `typing_extensions` `main` branch. Should I add another CI job that explicitly tests with `typing_extensions < 4.12.0`, to make sure that those tests continue to pass with older versions of `typing_extensions` also installed?

**Comment by sydney-runkle** [comment]
@AlexWaygood,

That sounds great re the additional CI job. Thank you!

**Comment by AlexWaygood** [comment]
Oh, but it looks like you already have a CI job for testing with your oldest supported version of `typing_extensions`, as well as a CI job for testing with the `typing_extensions` main branch:

https://github.com/pydantic/pydantic/blob/7061f36bc721ef4f173ef8f2e098f25e1eaea705/.github/workflows/ci.yml#L319-L327

So I'm not sure what I could add here @sydney-runkle. It seems like these code paths already have good test coverage, and that you already check in CI that the tests pass with your oldest supported version of `typing_extensions` and with the the `typing_extensions` main branch :-)

**Comment by sydney-runkle** [comment]
@AlexWaygood,

Great point. I'm happy to merge this then. Thanks for the awesome work here!

**Comment by AlexWaygood** [comment]
Brilliant -- thanks @sydney-runkle! :D

**Pull request merged**
