### PR TITLE
Add stacklevel to deprecationwarnings

### LINKED ISSUE #7908: Missing stacklevel to warnings.warn on deprecationwarnings
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

By default, `warnings.warn` only prints a message, and does not give a stack trace to the user so that they can know which part of their code triggered it.

Here is an example when using fastapi - from these warnings, I don't know what code I need to change.

```python
INFO:     Started reloader process [40] using StatReload
/usr/local/lib/python3.11/site-packages/pydantic/fields.py:798: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'escription'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:267: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
```

[Adding stacklevel=2 is considered good practice](https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/), so I recommend doing that here to make it easier for users who are migrating.

### Example Code

_No response_

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /usr/local/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep 20 2023, 07:59:41) [GCC 10.2.1 20210110]
                     platform: Linux-6.3.13-linuxkit-aarch64-with-glibc2.31
             related packages: mypy-1.6.1 fastapi-0.104.0 typing_extensions-4.8.0
```

### PR DESCRIPTION
**Pull request by thomasaarholt**
## Change Summary
Adds stacklevel to the warnings referred to in #7908

## Related issue number
fix #7908

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Above failures are due to pre-commit.
I might have to come back to this, as I maybe haven't fully understood how stacklevel is supposed to work. I might need a higher level, or something else funky is going on, since it now seems to be hiding some of the warnings.

**Comment by Viicos** [comment]
> I might have to come back to this, as I maybe haven't fully understood how stacklevel is supposed to work. I might need a higher level, or something else funky is going on, since it now seems to be hiding some of the warnings.

By default the `stacklevel` is set to 1, so the warning is emitted where it is defined (which isn't really useful for the 

Instead, it would be preferable to have the warning emitted where the deprecated object is being used. But there's no magic rule for this, as the call to `warnings.warn` can be nested multiple times.

A simple example:

```python
import warnings

def deprecated_func():
    warnings.warn("'deprecated_func' is deprecated", DeprecationWarning, stacklevel=1)  # the default

deprecated_func()
```

You will get the following warning:

```sh
/path/to/file.py:4: DeprecationWarning: 'deprecated_func' is deprecated
  warnings.warn("'deprecated_func' is deprecated", DeprecationWarning, stacklevel=1)
```

Not that useful, but using `stacklevel=2` instead:

```sh
/path/to/file.py:6: DeprecationWarning: 'deprecated_func' is deprecated
  deprecated_func()
```
The user will know where he his using the `deprecated_func`.

The issue is that you (as the maintainer of that `deprecated_func`) don't control how is it going to be called, and it is possible it is not called directly by the user.

Even worse, if you specify a `stacklevel` too high, it will simply not be emitted (e.g. try the preceding example with `stacklevel=3`).

**Comment by davidhewitt** [comment]
It would be a good idea to make tests for these changes, in pytest it's possible to capture the warnings emitted so that you can check they have the intended stack location. Using blanket `stacklevel=2` everywhere may or may not be correct depending on each particular warning, and refactoring code later might break this again and start producing nonsensical warning locations.

**Comment by sydney-runkle** [comment]
Happy to reopen this if/when we reopen the related issue 👍

**Pull request closed without merging**
