### PR TITLE
Add schema generation benchmarks for models with custom field and model validators

### LINKED ISSUE #9711: Expand breadth of benchmarks
We have a robust benchmark test suite in `pydantic-core`, but are lacking similar coverage in `pydantic`.

Specifically, I'm interested in expanding this test suite in relation to our core schema build times, as we're looking to improve performance there in the short term. Secondarily, I'm interested in better benchmarking for our json schema generation. Benchmarks for validation and serialization are great, but we've already got pretty good coverage in `pydantic-core` for those, so I'm less concerned about such benchmarks.

This is a great first issue - you can help write tests that test a variety of use cases for `pydantic`, without having to delve into the internals of `pydantic` code to fix bugs or add new features.

Here are some cases for which I think we should expand our suite of benchmarks (assume these are for core schema generation, but you can write related tests for any of the above mentioned categories). As in, you could read the first bullet as "we need to write some tests showcasing how long schema building takes for models with custom validators".

- [x] custom validators (field and model, also before, wrap, after, and plain)
- [x] tagged and untagged unions
- [x] stdlib types
- [x] second class Pydantic types like `SecretStr` and `PositiveInt`
- [x] custom serializers (field and model, also before, wrap, after, and plain)
- [x] recursive model definitions -- need much more robust testing when defs / refs are involved
- [ ] third party, custom types

I wouldn't say these are necessary to close this issue, but one thing for more involved contributors to look at would be benchmarking specific parts of our core schema generation process in `pydantic`, such as:

- [ ] annotation application
- [ ] discriminator application
- [ ] schema cleaning (including defs / refs simplification)
- [ ] schema walking
- [ ] field acquisition / setup in `ModelMetaClass.__new__`

### PR DESCRIPTION
**Pull request by AdolfoVillalobos**
## Change Summary

This PR expands the benchmark suite by adding "schema generation" benchmarks in the following cases:
- Models with custom field validators (before, wrap, after, and plain modes)
- Models with custom model validators (before, wrap and after modes)

I am open to suggestions. A benchmark mixing both model and field custom validators might be valuable.

## Related issue number

Contributes to #9711 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by sydney-runkle** [comment]
@AdolfoVillalobos, could you resolve the diff with `main` then I'll review? Thanks for another awesome PR!

**Comment by AdolfoVillalobos** [comment]
> @AdolfoVillalobos, could you resolve the diff with `main` then I'll review? Thanks for another awesome PR!

Done!  Thanks for the encouragement and patience ;) Happy to contribute.

**Review by sydney-runkle — CHANGES_REQUESTED** [review]
@AdolfoVillalobos,

Changes look great, but I wonder - perhaps we could break each case up into its own test? Ex - the wrap validator on its own, before validator on its own, etc.

This way, it'll be easier for us to track changes in performance on a case by case basis.

**Comment by AdolfoVillalobos** [comment]
> @AdolfoVillalobos,
> 
> Changes look great, but I wonder - perhaps we could break each case up into its own test? Ex - the wrap validator on its own, before validator on its own, etc.
> 
> This way, it'll be easier for us to track changes in performance on a case by case basis.

That makes total sense. I will take another shot ASAP. Thanks for the feedback!

**Comment by sydney-runkle** [comment]
@AdolfoVillalobos,

Fantastic! Ping me when you're ready for another review :).

**Pull request closed without merging**
