### PR TITLE
PYD-131 Links between API and usage docs

### PR DESCRIPTION
**Pull request by samuelcolvin**
Currently not working for docstrings on functions, @pawamoy any suggestions on how to fix this?

### CODE REVIEW

**Comment by pawamoy** [comment]
If by "not working" you mean that you get AliasResolutionErrors or similar, you can try to skip aliases:

```python
def update_docstrings_recursively(obj: GriffeObject, python_file_name: str) -> None:
    if obj.docstring:
        obj.docstring.value = update_docstring(obj, python_file_name)
    for member in obj.members.values():
        if not member.is_alias:
            update_docstrings_recursively(member, python_file_name)
```

The pre-condition is that the first object you pass to `update_docstrings_recursively` is not itself an alias (which shouldn't be the case if you call it from `visit_module`).

**Comment by pawamoy** [comment]
OK for some reason the condition mentioned above was not sufficient.

Tested this and it builds:

```python
def update_docstrings_recursively(obj: GriffeObject, python_file_name: str) -> None:
    if obj.is_alias:
        return
    if obj.docstring:
        obj.docstring.value = update_docstring(obj, python_file_name)
    for member in obj.members.values():
        update_docstrings_recursively(member, python_file_name)
```

**Comment by samuelcolvin** [comment]
more to do, but I think we should merge this.

**Comment by pawamoy** [comment]
Just a heads up letting you know that `VisitorExtension` and `InspectorExtension` will be deprecated in the next Griffe release. They were actually not flexible enough, and I reworked the extension system to make it more dev-friendly. Here is the updated code for the new, upcoming Extension:

```python
import ast
import re
from functools import partial
from pathlib import Path
from typing import Tuple

from griffe.dataclasses import Object as GriffeObject
from griffe.extensions import Extension
from griffe.agents.nodes import ObjectNode
from griffe.logger import get_logger
from pymdownx.slugs import slugify

DOCS_PATH = Path(__file__).parent.parent
slugifier = slugify(case='lower')
logger = get_logger(__name__)   # better than print

def find_heading(content: str, slug: str, file_path: Path) -> Tuple[str, int]:
    for m in re.finditer('^#+ (.+)', content, flags=re.M):
        heading = m.group(1)
        h_slug = slugifier(heading, '-')
        if h_slug == slug:
            return heading, m.end()
    raise ValueError(f'heading with slug {slug!r} not found in {file_path}')


def replace_links(m: re.Match, *, api_link: str) -> str:
    usage_path, slug = m.groups()
    rel_file = f'{usage_path}.md'
    file_path = DOCS_PATH / rel_file
    content = file_path.read_text()
    heading, heading_end = find_heading(content, slug, file_path)

    next_heading = re.search('^#+ ', content[heading_end:], flags=re.M)
    if next_heading:
        next_section = content[heading_end : heading_end + next_heading.start()]
    else:
        next_section = content[heading_end:]

    if f'[{api_link}]' not in next_section:
        logger.info(f'inserting API link "{api_link}" into {file_path.relative_to(DOCS_PATH)}')
        file_path.write_text(
            f'{content[:heading_end]}\n\n'
            '??? api "API Documentation"\n'
            f'    [`{api_link}`][{api_link}]<br>'
            f'{content[heading_end:]}'
        )

    return f'!!! abstract "Usage Documentation"\n    [{heading}](../{rel_file}#{slug})\n'


class DocLinksExtension(Extension):
    def on_instance(self, node: ast.AST | ObjectNode, obj: GriffeObject) -> None:
        if obj.docstring:
            obj.docstring.value = re.sub(
                r'usage[\- ]docs: ?https://docs\.pydantic\.dev/.+?/(.+?)/?#(\S+)',
                partial(replace_links, api_link=obj.path),
                obj.docstring.value,
                flags=re.I,
            ) 
```

**Pull request merged**
