### PR TITLE
Use ``is_valid_field`` from 1.x for ``mypy`` plugin

### PR DESCRIPTION
**Pull request by DanielNoord**
## Change Summary

https://github.com/pydantic/pydantic/blob/3ddb509786089f9df0658303545ae4b66db2d47c/pydantic/utils.py#L696-L699

This brings the `mypy` plugin in the `v1` namespace in line with how `1.x` actually behaved.

Importing this from the `pydantic` namespace created warnings in our v1/v2 codebase.

## Related issue number

No issue, couldn't find one and this seems like a simple enough change.

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist > seems unnecessary?
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

skip change file check

### CODE REVIEW

**Comment by DanielNoord** [comment]
please review

I think the last failing test can be skipped by adding the correct label? It doesn't feel like this requires a changelog?

**Comment by dmontagu** [comment]
In general I think we want to avoid changing the 1.X module code as much as possible.

Does it not work to change:
```python
from pydantic.utils import is_valid_field
```
to
```
from .utils import is_valid_field
```
?

**Comment by DanielNoord** [comment]
@dmontagu It should. Added a second commit to fix this, thanks!

**Review by sydney-runkle — APPROVED** [review]
Wonderful, thanks!

**Comment by DanielNoord** [comment]
@sydney-runkle Any reason why this fix is not included in the latest releases? The backport to `1.10.x` doesn't really resolve the issue, as the error is actually on the `2.x` tags.

**Comment by sydney-runkle** [comment]
@DanielNoord,

I think this should be included in 2.7!

**Pull request merged**
