### PR TITLE
Prep for v1.10.19 release

### PR DESCRIPTION
**Pull request by sydney-runkle**
Bump version and update release notes

### CODE REVIEW

**Review by hramezani — APPROVED** [review]

**Comment by asottile-sentry** [comment]
I realize this is a weird place to ask but...

- I noticed that there aren't cp313 wheels produced for 1.x -- would these be possible?
- I also noticed there's a bit in `setup.py` to prevent cython 3.x -- though it seems to build and import cleanly (and perhaps would allow a more "future-proof" buildability for future python versions, perhaps even with `abi3` support meaning we would never need a recompile)

I mostly ask because sentry (an [investor / sponsor of pydantic](https://pydantic.dev/articles/company-announcement)) is currently hard-stuck on 1.x (2.x introduces severe performance degredation for our workflows) and we're currently weighing either forking to re-add speedup builds capability or abandoning pydantic altogether and figured I'd float the idea of just fixing this upstream directly before doing so

**Comment by Viicos** [comment]
> * I noticed that there aren't cp313 wheels produced for 1.x -- would these be possible?

I opened https://github.com/pydantic/pydantic/pull/10847 to add 3.13 to the list of builds.

> * I also noticed there's a bit in `setup.py` to prevent cython 3.x -- though it seems to build and import cleanly

I'm not too familiar with Cython and how much work it represents to switch from 0.x to 3.x. There's some discussion about it [here](https://github.com/pydantic/pydantic/pull/9644#discussion_r1636713269), and I recall seeing a code comment stating that we won't build on 3.x (no reason mentioned :/).

We're currently working on model build times improvements. Hopefully you'll be able to switch to v2 at sentry at some point. I'm assuming most of your Pydantic usage is from [`RpcModel`](https://github.com/getsentry/sentry/blob/57f40229e2b08c3f2a1af8b14c93a0782a72b77b/src/sentry/hybridcloud/rpc/__init__.py#L42) subclasses?

**Comment by asottile-sentry** [comment]
the reason I mentioned cython 3.x is it is required to build for 3.13+

**Comment by Viicos** [comment]
Yeah just noticed this on my open PR. I can take a deeper look tomorrow.

**Comment by Viicos** [comment]
1.10.20 was published with proper wheels for 3.13.

**Pull request merged**
